-- Migration: Update kode_unit in unit_kerja based on ref_satker_relationship.xlsx
-- Run this in Supabase SQL editor

UPDATE unit_kerja SET kode_unit = 'E1-U' WHERE nama_unit = 'Direktorat Jenderal Badan Peradilan Umum';
UPDATE unit_kerja SET kode_unit = 'E1-A' WHERE nama_unit = 'Direktorat Jenderal Badan Peradilan Agama';
UPDATE unit_kerja SET kode_unit = 'E1-MTUN' WHERE nama_unit = 'Direktorat Jenderal Badan Peradilan Militer Dan Peradilan Tata Usaha Negara';
UPDATE unit_kerja SET kode_unit = 'E1-BSDK' WHERE nama_unit = 'Badan Penelitian Dan Pengembangan Dan Pendidikan Dan Pelatihan Hukum Dan Peradilan';
UPDATE unit_kerja SET kode_unit = 'E1-BP' WHERE nama_unit = 'Badan Pengawasan';
UPDATE unit_kerja SET kode_unit = 'E1-BUA' WHERE nama_unit = 'Badan Urusan Administrasi';
UPDATE unit_kerja SET kode_unit = 'E1-K' WHERE nama_unit = 'Kepaniteraan';
UPDATE unit_kerja SET kode_unit = '401582' WHERE nama_unit = 'Mahkamah Syar''iyah Aceh';
UPDATE unit_kerja SET kode_unit = '401591' WHERE nama_unit = 'Mahkamah Syar''iyah Banda Aceh';
UPDATE unit_kerja SET kode_unit = '401633' WHERE nama_unit = 'Mahkamah Syar''iyah Bireuen';
UPDATE unit_kerja SET kode_unit = '401709' WHERE nama_unit = 'Mahkamah Syar''iyah Blangkajeren';
UPDATE unit_kerja SET kode_unit = '401965' WHERE nama_unit = 'Mahkamah Syar''iyah Blangpidie';
UPDATE unit_kerja SET kode_unit = '401746' WHERE nama_unit = 'Mahkamah Syar''iyah Calang';
UPDATE unit_kerja SET kode_unit = '401670' WHERE nama_unit = 'Mahkamah Syar''iyah Idi';
UPDATE unit_kerja SET kode_unit = '402607' WHERE nama_unit = 'Mahkamah Syar''iyah Jantho';
UPDATE unit_kerja SET kode_unit = '401967' WHERE nama_unit = 'Mahkamah Syar''iyah Kota Subulussalam';
UPDATE unit_kerja SET kode_unit = '401695' WHERE nama_unit = 'Mahkamah Syar''iyah Kuala Simpang';
UPDATE unit_kerja SET kode_unit = '401715' WHERE nama_unit = 'Mahkamah Syar''iyah Kutacane';
UPDATE unit_kerja SET kode_unit = '401689' WHERE nama_unit = 'Mahkamah Syar''iyah Langsa';
UPDATE unit_kerja SET kode_unit = '401642' WHERE nama_unit = 'Mahkamah Syar''iyah Lhoksukon';
UPDATE unit_kerja SET kode_unit = '401664' WHERE nama_unit = 'Mahkamah Syar''iyah Lhokseumawe';
UPDATE unit_kerja SET kode_unit = '401721' WHERE nama_unit = 'Mahkamah Syar''iyah Meulaboh';
UPDATE unit_kerja SET kode_unit = '401627' WHERE nama_unit = 'Mahkamah Syar''iyah Meureudu';
UPDATE unit_kerja SET kode_unit = '401602' WHERE nama_unit = 'Mahkamah Syar''iyah Sabang';
UPDATE unit_kerja SET kode_unit = '401611' WHERE nama_unit = 'Mahkamah Syar''iyah Sigli';
UPDATE unit_kerja SET kode_unit = '682228' WHERE nama_unit = 'Mahkamah Syar''iyah Simpang Tiga Redelong';
UPDATE unit_kerja SET kode_unit = '401730' WHERE nama_unit = 'Mahkamah Syar''iyah Sinabang';
UPDATE unit_kerja SET kode_unit = '401752' WHERE nama_unit = 'Mahkamah Syar''iyah Singkil';
UPDATE unit_kerja SET kode_unit = '401966' WHERE nama_unit = 'Mahkamah Syar''iyah Suka Makmue';
UPDATE unit_kerja SET kode_unit = '401658' WHERE nama_unit = 'Mahkamah Syar''iyah Takengon';
UPDATE unit_kerja SET kode_unit = '401761' WHERE nama_unit = 'Mahkamah Syar''iyah Tapak Tuan';
UPDATE unit_kerja SET kode_unit = '402593' WHERE nama_unit = 'Pengadilan Agama Ambarawa';
UPDATE unit_kerja SET kode_unit = '307754' WHERE nama_unit = 'Pengadilan Agama Ambon';
UPDATE unit_kerja SET kode_unit = '401884' WHERE nama_unit = 'Pengadilan Agama Ampana';
UPDATE unit_kerja SET kode_unit = '402556' WHERE nama_unit = 'Pengadilan Agama Amuntai';
UPDATE unit_kerja SET kode_unit = '682171' WHERE nama_unit = 'Pengadilan Agama Amurang';
UPDATE unit_kerja SET kode_unit = '682207' WHERE nama_unit = 'Pengadilan Agama Andoolo';
UPDATE unit_kerja SET kode_unit = '308035' WHERE nama_unit = 'Pengadilan Agama Arga Makmur';
UPDATE unit_kerja SET kode_unit = '682300' WHERE nama_unit = 'Pengadilan Agama Arso';
UPDATE unit_kerja SET kode_unit = '402814' WHERE nama_unit = 'Pengadilan Agama Atambua';
UPDATE unit_kerja SET kode_unit = '614731' WHERE nama_unit = 'Pengadilan Agama Badung';
UPDATE unit_kerja SET kode_unit = '402845' WHERE nama_unit = 'Pengadilan Agama Bajawa';
UPDATE unit_kerja SET kode_unit = '401865' WHERE nama_unit = 'Pengadilan Agama Balige';
UPDATE unit_kerja SET kode_unit = '307199' WHERE nama_unit = 'Pengadilan Agama Balikpapan';
UPDATE unit_kerja SET kode_unit = '400662' WHERE nama_unit = 'Pengadilan Agama Bandung';
UPDATE unit_kerja SET kode_unit = '652123' WHERE nama_unit = 'Pengadilan Agama Banggai';
UPDATE unit_kerja SET kode_unit = '401441' WHERE nama_unit = 'Pengadilan Agama Bangil';
UPDATE unit_kerja SET kode_unit = '401545' WHERE nama_unit = 'Pengadilan Agama Bangkalan';
UPDATE unit_kerja SET kode_unit = '402101' WHERE nama_unit = 'Pengadilan Agama Bangkinang';
UPDATE unit_kerja SET kode_unit = '402211' WHERE nama_unit = 'Pengadilan Agama Bangko';
UPDATE unit_kerja SET kode_unit = '402726' WHERE nama_unit = 'Pengadilan Agama Bangli';
UPDATE unit_kerja SET kode_unit = '682164' WHERE nama_unit = 'Pengadilan Agama Banjar';
UPDATE unit_kerja SET kode_unit = '632043' WHERE nama_unit = 'Pengadilan Agama Banjarbaru';
UPDATE unit_kerja SET kode_unit = '402500' WHERE nama_unit = 'Pengadilan Agama Banjarmasin';
UPDATE unit_kerja SET kode_unit = '401106' WHERE nama_unit = 'Pengadilan Agama Banjarnegara';
UPDATE unit_kerja SET kode_unit = '307534' WHERE nama_unit = 'Pengadilan Agama Bantaeng';
UPDATE unit_kerja SET kode_unit = '401225' WHERE nama_unit = 'Pengadilan Agama Bantul';
UPDATE unit_kerja SET kode_unit = '401070' WHERE nama_unit = 'Pengadilan Agama Banyumas';
UPDATE unit_kerja SET kode_unit = '401369' WHERE nama_unit = 'Pengadilan Agama Banyuwangi';
UPDATE unit_kerja SET kode_unit = '402540' WHERE nama_unit = 'Pengadilan Agama Barabai';
UPDATE unit_kerja SET kode_unit = '307487' WHERE nama_unit = 'Pengadilan Agama Barru';
UPDATE unit_kerja SET kode_unit = '547699' WHERE nama_unit = 'Pengadilan Agama Batam';
UPDATE unit_kerja SET kode_unit = '400905' WHERE nama_unit = 'Pengadilan Agama Batang';
UPDATE unit_kerja SET kode_unit = '682260' WHERE nama_unit = 'Pengadilan Agama Batu Licin';
UPDATE unit_kerja SET kode_unit = '402267' WHERE nama_unit = 'Pengadilan Agama Baturaja';
UPDATE unit_kerja SET kode_unit = '401947' WHERE nama_unit = 'Pengadilan Agama Batusangkar';
UPDATE unit_kerja SET kode_unit = '307729' WHERE nama_unit = 'Pengadilan Agama Bau';
UPDATE unit_kerja SET kode_unit = '401287' WHERE nama_unit = 'Pengadilan Agama Bawean';
UPDATE unit_kerja SET kode_unit = '400832' WHERE nama_unit = 'Pengadilan Agama Bekasi';
UPDATE unit_kerja SET kode_unit = '401879' WHERE nama_unit = 'Pengadilan Agama Belopa';
UPDATE unit_kerja SET kode_unit = '402117' WHERE nama_unit = 'Pengadilan Agama Bengkalis';
UPDATE unit_kerja SET kode_unit = '632039' WHERE nama_unit = 'Pengadilan Agama Bengkayang';
UPDATE unit_kerja SET kode_unit = '308152' WHERE nama_unit = 'Pengadilan Agama Bengkulu';
UPDATE unit_kerja SET kode_unit = '402891' WHERE nama_unit = 'Pengadilan Agama Biak';
UPDATE unit_kerja SET kode_unit = '307928' WHERE nama_unit = 'Pengadilan Agama Bima';
UPDATE unit_kerja SET kode_unit = '401783' WHERE nama_unit = 'Pengadilan Agama Binjai';
UPDATE unit_kerja SET kode_unit = '401940' WHERE nama_unit = 'Pengadilan Agama Bintuhan';
UPDATE unit_kerja SET kode_unit = '604751' WHERE nama_unit = 'Pengadilan Agama Bitung';
UPDATE unit_kerja SET kode_unit = '652055' WHERE nama_unit = 'Pengadilan Agama Blambangan Umpu';
UPDATE unit_kerja SET kode_unit = '401401' WHERE nama_unit = 'Pengadilan Agama Blitar';
UPDATE unit_kerja SET kode_unit = '401002' WHERE nama_unit = 'Pengadilan Agama Blora';
UPDATE unit_kerja SET kode_unit = '400729' WHERE nama_unit = 'Pengadilan Agama Bogor';
UPDATE unit_kerja SET kode_unit = '401307' WHERE nama_unit = 'Pengadilan Agama Bojonegoro';
UPDATE unit_kerja SET kode_unit = '401889' WHERE nama_unit = 'Pengadilan Agama Bolaang Uki';
UPDATE unit_kerja SET kode_unit = '401344' WHERE nama_unit = 'Pengadilan Agama Bondowoso';
UPDATE unit_kerja SET kode_unit = '652080' WHERE nama_unit = 'Pengadilan Agama Bontang';
UPDATE unit_kerja SET kode_unit = '401890' WHERE nama_unit = 'Pengadilan Agama Boroko';
UPDATE unit_kerja SET kode_unit = '401137' WHERE nama_unit = 'Pengadilan Agama Boyolali';
UPDATE unit_kerja SET kode_unit = '400891' WHERE nama_unit = 'Pengadilan Agama Brebes';
UPDATE unit_kerja SET kode_unit = '402010' WHERE nama_unit = 'Pengadilan Agama Bukittinggi';
UPDATE unit_kerja SET kode_unit = '307541' WHERE nama_unit = 'Pengadilan Agama Bulukumba';
UPDATE unit_kerja SET kode_unit = '652119' WHERE nama_unit = 'Pengadilan Agama Bungku';
UPDATE unit_kerja SET kode_unit = '402452' WHERE nama_unit = 'Pengadilan Agama Buntok';
UPDATE unit_kerja SET kode_unit = '652102' WHERE nama_unit = 'Pengadilan Agama Buol';
UPDATE unit_kerja SET kode_unit = '400690' WHERE nama_unit = 'Pengadilan Agama Ciamis';
UPDATE unit_kerja SET kode_unit = '400741' WHERE nama_unit = 'Pengadilan Agama Cianjur';
UPDATE unit_kerja SET kode_unit = '402995' WHERE nama_unit = 'Pengadilan Agama Cibadak';
UPDATE unit_kerja SET kode_unit = '604719' WHERE nama_unit = 'Pengadilan Agama Cibinong';
UPDATE unit_kerja SET kode_unit = '614706' WHERE nama_unit = 'Pengadilan Agama Cikarang';
UPDATE unit_kerja SET kode_unit = '401086' WHERE nama_unit = 'Pengadilan Agama Cilacap';
UPDATE unit_kerja SET kode_unit = '652076' WHERE nama_unit = 'Pengadilan Agama Cilegon';
UPDATE unit_kerja SET kode_unit = '400750' WHERE nama_unit = 'Pengadilan Agama Cirebon';
UPDATE unit_kerja SET kode_unit = '308021' WHERE nama_unit = 'Pengadilan Agama Curup';
UPDATE unit_kerja SET kode_unit = '402154' WHERE nama_unit = 'Pengadilan Agama Dabo Singkep';
UPDATE unit_kerja SET kode_unit = '401895' WHERE nama_unit = 'Pengadilan Agama Dataran Hunimoa';
UPDATE unit_kerja SET kode_unit = '401894' WHERE nama_unit = 'Pengadilan Agama Dataran Hunipopu';
UPDATE unit_kerja SET kode_unit = '400942' WHERE nama_unit = 'Pengadilan Agama Demak';
UPDATE unit_kerja SET kode_unit = '307822' WHERE nama_unit = 'Pengadilan Agama Denpasar';
UPDATE unit_kerja SET kode_unit = '652062' WHERE nama_unit = 'Pengadilan Agama Depok';
UPDATE unit_kerja SET kode_unit = '307932' WHERE nama_unit = 'Pengadilan Agama Dompu';
UPDATE unit_kerja SET kode_unit = '604765' WHERE nama_unit = 'Pengadilan Agama Donggala';
UPDATE unit_kerja SET kode_unit = '402622' WHERE nama_unit = 'Pengadilan Agama Dumai';
UPDATE unit_kerja SET kode_unit = '307974' WHERE nama_unit = 'Pengadilan Agama Ende';
UPDATE unit_kerja SET kode_unit = '307597' WHERE nama_unit = 'Pengadilan Agama Enrekang';
UPDATE unit_kerja SET kode_unit = '402902' WHERE nama_unit = 'Pengadilan Agama Fak';
UPDATE unit_kerja SET kode_unit = '400710' WHERE nama_unit = 'Pengadilan Agama Garut';
UPDATE unit_kerja SET kode_unit = '401950' WHERE nama_unit = 'Pengadilan Agama Gedong Tataan';
UPDATE unit_kerja SET kode_unit = '402772' WHERE nama_unit = 'Pengadilan Agama Gianyar';
UPDATE unit_kerja SET kode_unit = '614727' WHERE nama_unit = 'Pengadilan Agama Giri Menang';
UPDATE unit_kerja SET kode_unit = '307250' WHERE nama_unit = 'Pengadilan Agama Gorontalo';
UPDATE unit_kerja SET kode_unit = '401293' WHERE nama_unit = 'Pengadilan Agama Gresik';
UPDATE unit_kerja SET kode_unit = '401896' WHERE nama_unit = 'Pengadilan Agama Gunung Sitoli';
UPDATE unit_kerja SET kode_unit = '652041' WHERE nama_unit = 'Pengadilan Agama Gunung Sugih';
UPDATE unit_kerja SET kode_unit = '400766' WHERE nama_unit = 'Pengadilan Agama Indramayu';
UPDATE unit_kerja SET kode_unit = '400631' WHERE nama_unit = 'Pengadilan Agama Jakarta Barat';
UPDATE unit_kerja SET kode_unit = '400616' WHERE nama_unit = 'Pengadilan Agama Jakarta Pusat';
UPDATE unit_kerja SET kode_unit = '400653' WHERE nama_unit = 'Pengadilan Agama Jakarta Selatan';
UPDATE unit_kerja SET kode_unit = '400647' WHERE nama_unit = 'Pengadilan Agama Jakarta Timur';
UPDATE unit_kerja SET kode_unit = '400622' WHERE nama_unit = 'Pengadilan Agama Jakarta Utara';
UPDATE unit_kerja SET kode_unit = '402185' WHERE nama_unit = 'Pengadilan Agama Jambi';
UPDATE unit_kerja SET kode_unit = '402876' WHERE nama_unit = 'Pengadilan Agama Jayapura';
UPDATE unit_kerja SET kode_unit = '401338' WHERE nama_unit = 'Pengadilan Agama Jember';
UPDATE unit_kerja SET kode_unit = '307466' WHERE nama_unit = 'Pengadilan Agama Jeneponto';
UPDATE unit_kerja SET kode_unit = '400982' WHERE nama_unit = 'Pengadilan Agama Jepara';
UPDATE unit_kerja SET kode_unit = '401271' WHERE nama_unit = 'Pengadilan Agama Jombang';
UPDATE unit_kerja SET kode_unit = '401792' WHERE nama_unit = 'Pengadilan Agama Kabanjahe';
UPDATE unit_kerja SET kode_unit = '401375' WHERE nama_unit = 'Pengadilan Agama Kabupaten Kediri';
UPDATE unit_kerja SET kode_unit = '403030' WHERE nama_unit = 'Pengadilan Agama Kabupaten Madiun';
UPDATE unit_kerja SET kode_unit = '604730' WHERE nama_unit = 'Pengadilan Agama Kabupaten Malang';
UPDATE unit_kerja SET kode_unit = '401899' WHERE nama_unit = 'Pengadilan Agama Kaimana';
UPDATE unit_kerja SET kode_unit = '614710' WHERE nama_unit = 'Pengadilan Agama Kajen';
UPDATE unit_kerja SET kode_unit = '307960' WHERE nama_unit = 'Pengadilan Agama Kalabahi';
UPDATE unit_kerja SET kode_unit = '402644' WHERE nama_unit = 'Pengadilan Agama Kalianda';
UPDATE unit_kerja SET kode_unit = '402531' WHERE nama_unit = 'Pengadilan Agama Kandangan';
UPDATE unit_kerja SET kode_unit = '401576' WHERE nama_unit = 'Pengadilan Agama Kangean';
UPDATE unit_kerja SET kode_unit = '401174' WHERE nama_unit = 'Pengadilan Agama Karanganyar';
UPDATE unit_kerja SET kode_unit = '402741' WHERE nama_unit = 'Pengadilan Agama Karangasem';
UPDATE unit_kerja SET kode_unit = '400848' WHERE nama_unit = 'Pengadilan Agama Karawang';
UPDATE unit_kerja SET kode_unit = '401873' WHERE nama_unit = 'Pengadilan Agama Kasongan';
UPDATE unit_kerja SET kode_unit = '402273' WHERE nama_unit = 'Pengadilan Agama Kayuagung';
UPDATE unit_kerja SET kode_unit = '401055' WHERE nama_unit = 'Pengadilan Agama Kebumen';
UPDATE unit_kerja SET kode_unit = '402839' WHERE nama_unit = 'Pengadilan Agama Kefamenanu';
UPDATE unit_kerja SET kode_unit = '400936' WHERE nama_unit = 'Pengadilan Agama Kendal';
UPDATE unit_kerja SET kode_unit = '307712' WHERE nama_unit = 'Pengadilan Agama Kendari';
UPDATE unit_kerja SET kode_unit = '401942' WHERE nama_unit = 'Pengadilan Agama Kepahiang';
UPDATE unit_kerja SET kode_unit = '402386' WHERE nama_unit = 'Pengadilan Agama Ketapang';
UPDATE unit_kerja SET kode_unit = '403061' WHERE nama_unit = 'Pengadilan Agama Kisaran';
UPDATE unit_kerja SET kode_unit = '401121' WHERE nama_unit = 'Pengadilan Agama Klaten';
UPDATE unit_kerja SET kode_unit = '402763' WHERE nama_unit = 'Pengadilan Agama Klungkung';
UPDATE unit_kerja SET kode_unit = '307690' WHERE nama_unit = 'Pengadilan Agama Kolaka';
UPDATE unit_kerja SET kode_unit = '401958' WHERE nama_unit = 'Pengadilan Agama Kota Cimahi';
UPDATE unit_kerja SET kode_unit = '403046' WHERE nama_unit = 'Pengadilan Agama Kota Kediri';
UPDATE unit_kerja SET kode_unit = '401488' WHERE nama_unit = 'Pengadilan Agama Kota Madiun';
UPDATE unit_kerja SET kode_unit = '401426' WHERE nama_unit = 'Pengadilan Agama Kota Malang';
UPDATE unit_kerja SET kode_unit = '682232' WHERE nama_unit = 'Pengadilan Agama Kota Padang Sidempuan';
UPDATE unit_kerja SET kode_unit = '682150' WHERE nama_unit = 'Pengadilan Agama Kota Tasikmalaya';
UPDATE unit_kerja SET kode_unit = '307122' WHERE nama_unit = 'Pengadilan Agama Kotabaru';
UPDATE unit_kerja SET kode_unit = '402349' WHERE nama_unit = 'Pengadilan Agama Kotabumi';
UPDATE unit_kerja SET kode_unit = '307232' WHERE nama_unit = 'Pengadilan Agama Kotamobagu';
UPDATE unit_kerja SET kode_unit = '401984' WHERE nama_unit = 'Pengadilan Agama Koto Baru';
UPDATE unit_kerja SET kode_unit = '401463' WHERE nama_unit = 'Pengadilan Agama Kraksaan';
UPDATE unit_kerja SET kode_unit = '402330' WHERE nama_unit = 'Pengadilan Agama Krui';
UPDATE unit_kerja SET kode_unit = '402468' WHERE nama_unit = 'Pengadilan Agama Kuala Kapuas';
UPDATE unit_kerja SET kode_unit = '401876' WHERE nama_unit = 'Pengadilan Agama Kuala Kurun';
UPDATE unit_kerja SET kode_unit = '401870' WHERE nama_unit = 'Pengadilan Agama Kuala Pembuang';
UPDATE unit_kerja SET kode_unit = '402205' WHERE nama_unit = 'Pengadilan Agama Kuala Tungkal';
UPDATE unit_kerja SET kode_unit = '400973' WHERE nama_unit = 'Pengadilan Agama Kudus';
UPDATE unit_kerja SET kode_unit = '400781' WHERE nama_unit = 'Pengadilan Agama Kuningan';
UPDATE unit_kerja SET kode_unit = '307953' WHERE nama_unit = 'Pengadilan Agama Kupang';
UPDATE unit_kerja SET kode_unit = '401893' WHERE nama_unit = 'Pengadilan Agama Kwandang';
UPDATE unit_kerja SET kode_unit = '682281' WHERE nama_unit = 'Pengadilan Agama Labuan Bajo';
UPDATE unit_kerja SET kode_unit = '307818' WHERE nama_unit = 'Pengadilan Agama Labuha';
UPDATE unit_kerja SET kode_unit = '402251' WHERE nama_unit = 'Pengadilan Agama Lahat';
UPDATE unit_kerja SET kode_unit = '401322' WHERE nama_unit = 'Pengadilan Agama Lamongan';
UPDATE unit_kerja SET kode_unit = '402794' WHERE nama_unit = 'Pengadilan Agama Larantuka';
UPDATE unit_kerja SET kode_unit = '401886' WHERE nama_unit = 'Pengadilan Agama Lasusua';
UPDATE unit_kerja SET kode_unit = '682253' WHERE nama_unit = 'Pengadilan Agama Lebong';
UPDATE unit_kerja SET kode_unit = '632064' WHERE nama_unit = 'Pengadilan Agama Lewoleba';
UPDATE unit_kerja SET kode_unit = '402690' WHERE nama_unit = 'Pengadilan Agama Limboto';
UPDATE unit_kerja SET kode_unit = '401888' WHERE nama_unit = 'Pengadilan Agama Lolak';
UPDATE unit_kerja SET kode_unit = '402613' WHERE nama_unit = 'Pengadilan Agama Lubuk Basung';
UPDATE unit_kerja SET kode_unit = '402298' WHERE nama_unit = 'Pengadilan Agama Lubuk Linggau';
UPDATE unit_kerja SET kode_unit = '403077' WHERE nama_unit = 'Pengadilan Agama Lubuk Pakam';
UPDATE unit_kerja SET kode_unit = '402029' WHERE nama_unit = 'Pengadilan Agama Lubuk Sikaping';
UPDATE unit_kerja SET kode_unit = '401472' WHERE nama_unit = 'Pengadilan Agama Lumajang';
UPDATE unit_kerja SET kode_unit = '307300' WHERE nama_unit = 'Pengadilan Agama Luwuk';
UPDATE unit_kerja SET kode_unit = '401018' WHERE nama_unit = 'Pengadilan Agama Magelang';
UPDATE unit_kerja SET kode_unit = '401494' WHERE nama_unit = 'Pengadilan Agama Magetan';
UPDATE unit_kerja SET kode_unit = '400772' WHERE nama_unit = 'Pengadilan Agama Majalengka';
UPDATE unit_kerja SET kode_unit = '307644' WHERE nama_unit = 'Pengadilan Agama Majene';
UPDATE unit_kerja SET kode_unit = '307623' WHERE nama_unit = 'Pengadilan Agama Makale';
UPDATE unit_kerja SET kode_unit = '307452' WHERE nama_unit = 'Pengadilan Agama Makassar';
UPDATE unit_kerja SET kode_unit = '401883' WHERE nama_unit = 'Pengadilan Agama Malili';
UPDATE unit_kerja SET kode_unit = '307651' WHERE nama_unit = 'Pengadilan Agama Mamuju';
UPDATE unit_kerja SET kode_unit = '307225' WHERE nama_unit = 'Pengadilan Agama Manado';
UPDATE unit_kerja SET kode_unit = '402041' WHERE nama_unit = 'Pengadilan Agama Maninjau';
UPDATE unit_kerja SET kode_unit = '308014' WHERE nama_unit = 'Pengadilan Agama Manna';
UPDATE unit_kerja SET kode_unit = '402911' WHERE nama_unit = 'Pengadilan Agama Manokwari';
UPDATE unit_kerja SET kode_unit = '307101' WHERE nama_unit = 'Pengadilan Agama Marabahan';
UPDATE unit_kerja SET kode_unit = '682185' WHERE nama_unit = 'Pengadilan Agama Marisa';
UPDATE unit_kerja SET kode_unit = '307445' WHERE nama_unit = 'Pengadilan Agama Maros';
UPDATE unit_kerja SET kode_unit = '401944' WHERE nama_unit = 'Pengadilan Agama Martapura (Sumsel)';
UPDATE unit_kerja SET kode_unit = '402519' WHERE nama_unit = 'Pengadilan Agama Martapura (Kalsel)';
UPDATE unit_kerja SET kode_unit = '632050' WHERE nama_unit = 'Pengadilan Agama Masamba';
UPDATE unit_kerja SET kode_unit = '307775' WHERE nama_unit = 'Pengadilan Agama Masohi';
UPDATE unit_kerja SET kode_unit = '307885' WHERE nama_unit = 'Pengadilan Agama Mataram';
UPDATE unit_kerja SET kode_unit = '402851' WHERE nama_unit = 'Pengadilan Agama Maumere';
UPDATE unit_kerja SET kode_unit = '401803' WHERE nama_unit = 'Pengadilan Agama Medan';
UPDATE unit_kerja SET kode_unit = '402669' WHERE nama_unit = 'Pengadilan Agama Mempawah';
UPDATE unit_kerja SET kode_unit = '682249' WHERE nama_unit = 'Pengadilan Agama Mentok';
UPDATE unit_kerja SET kode_unit = '402958' WHERE nama_unit = 'Pengadilan Agama Merauke';
UPDATE unit_kerja SET kode_unit = '401952' WHERE nama_unit = 'Pengadilan Agama Mesuji';
UPDATE unit_kerja SET kode_unit = '402355' WHERE nama_unit = 'Pengadilan Agama Metro';
UPDATE unit_kerja SET kode_unit = '614773' WHERE nama_unit = 'Pengadilan Agama Mimika';
UPDATE unit_kerja SET kode_unit = '401256' WHERE nama_unit = 'Pengadilan Agama Mojokerto';
UPDATE unit_kerja SET kode_unit = '307796' WHERE nama_unit = 'Pengadilan Agama Morotai';
UPDATE unit_kerja SET kode_unit = '403052' WHERE nama_unit = 'Pengadilan Agama Muara Bulian';
UPDATE unit_kerja SET kode_unit = '402191' WHERE nama_unit = 'Pengadilan Agama Muara Bungo';
UPDATE unit_kerja SET kode_unit = '402282' WHERE nama_unit = 'Pengadilan Agama Muara Enim';
UPDATE unit_kerja SET kode_unit = '401990' WHERE nama_unit = 'Pengadilan Agama Muara Labuh';
UPDATE unit_kerja SET kode_unit = '632022' WHERE nama_unit = 'Pengadilan Agama Muara Sabak';
UPDATE unit_kerja SET kode_unit = '652020' WHERE nama_unit = 'Pengadilan Agama Muara Tebo';
UPDATE unit_kerja SET kode_unit = '402443' WHERE nama_unit = 'Pengadilan Agama Muara Teweh';
UPDATE unit_kerja SET kode_unit = '401945' WHERE nama_unit = 'Pengadilan Agama Muaradua';
UPDATE unit_kerja SET kode_unit = '401939' WHERE nama_unit = 'Pengadilan Agama Mukomuko';
UPDATE unit_kerja SET kode_unit = '403021' WHERE nama_unit = 'Pengadilan Agama Mungkid';
UPDATE unit_kerja SET kode_unit = '402927' WHERE nama_unit = 'Pengadilan Agama Nabire';
UPDATE unit_kerja SET kode_unit = '401898' WHERE nama_unit = 'Pengadilan Agama Namlea';
UPDATE unit_kerja SET kode_unit = '401868' WHERE nama_unit = 'Pengadilan Agama Nanga Bulik';
UPDATE unit_kerja SET kode_unit = '401961' WHERE nama_unit = 'Pengadilan Agama Nanga Pinoh';
UPDATE unit_kerja SET kode_unit = '614670' WHERE nama_unit = 'Pengadilan Agama Natuna';
UPDATE unit_kerja SET kode_unit = '402571' WHERE nama_unit = 'Pengadilan Agama Negara';
UPDATE unit_kerja SET kode_unit = '402732' WHERE nama_unit = 'Pengadilan Agama Negara (Kalsel)';
UPDATE unit_kerja SET kode_unit = '401959' WHERE nama_unit = 'Pengadilan Agama Ngamprah';
UPDATE unit_kerja SET kode_unit = '401410' WHERE nama_unit = 'Pengadilan Agama Nganjuk';
UPDATE unit_kerja SET kode_unit = '401508' WHERE nama_unit = 'Pengadilan Agama Ngawi';
UPDATE unit_kerja SET kode_unit = '682295' WHERE nama_unit = 'Pengadilan Agama Nunukan';
UPDATE unit_kerja SET kode_unit = '401520' WHERE nama_unit = 'Pengadilan Agama Pacitan';
UPDATE unit_kerja SET kode_unit = '401953' WHERE nama_unit = 'Pengadilan Agama Padang';
UPDATE unit_kerja SET kode_unit = '401962' WHERE nama_unit = 'Pengadilan Agama Padang Panjang';
UPDATE unit_kerja SET kode_unit = '401880' WHERE nama_unit = 'Pengadilan Agama Padang Sidempuan';
UPDATE unit_kerja SET kode_unit = '401946' WHERE nama_unit = 'Pengadilan Agama Pagar Alam';
UPDATE unit_kerja SET kode_unit = '402004' WHERE nama_unit = 'Pengadilan Agama Painan';
UPDATE unit_kerja SET kode_unit = '402421' WHERE nama_unit = 'Pengadilan Agama Palangkaraya';
UPDATE unit_kerja SET kode_unit = '402242' WHERE nama_unit = 'Pengadilan Agama Palembang';
UPDATE unit_kerja SET kode_unit = '307619' WHERE nama_unit = 'Pengadilan Agama Palopo';
UPDATE unit_kerja SET kode_unit = '307271' WHERE nama_unit = 'Pengadilan Agama Palu';
UPDATE unit_kerja SET kode_unit = '401539' WHERE nama_unit = 'Pengadilan Agama Pamekasan';
UPDATE unit_kerja SET kode_unit = '604744' WHERE nama_unit = 'Pengadilan Agama Pandan';
UPDATE unit_kerja SET kode_unit = '417850' WHERE nama_unit = 'Pengadilan Agama Pandeglang';
UPDATE unit_kerja SET kode_unit = '307431' WHERE nama_unit = 'Pengadilan Agama Pangkajene';
UPDATE unit_kerja SET kode_unit = '401943' WHERE nama_unit = 'Pengadilan Agama Pangkalan Balai';
UPDATE unit_kerja SET kode_unit = '402437' WHERE nama_unit = 'Pengadilan Agama Pangkalan Bun';
UPDATE unit_kerja SET kode_unit = '631999' WHERE nama_unit = 'Pengadilan Agama Pangkalan Kerinci';
UPDATE unit_kerja SET kode_unit = '402302' WHERE nama_unit = 'Pengadilan Agama Pangkalpinang';
UPDATE unit_kerja SET kode_unit = '614780' WHERE nama_unit = 'Pengadilan Agama Paniai';
UPDATE unit_kerja SET kode_unit = '631982' WHERE nama_unit = 'Pengadilan Agama Panyabungan';
UPDATE unit_kerja SET kode_unit = '307576' WHERE nama_unit = 'Pengadilan Agama Parepare';
UPDATE unit_kerja SET kode_unit = '401916' WHERE nama_unit = 'Pengadilan Agama Pariaman';
UPDATE unit_kerja SET kode_unit = '682192' WHERE nama_unit = 'Pengadilan Agama Parigi';
UPDATE unit_kerja SET kode_unit = '401882' WHERE nama_unit = 'Pengadilan Agama Pasangkayu';
UPDATE unit_kerja SET kode_unit = '682211' WHERE nama_unit = 'Pengadilan Agama Pasarwajo';
UPDATE unit_kerja SET kode_unit = '402123' WHERE nama_unit = 'Pengadilan Agama Pasir Pangaraian';
UPDATE unit_kerja SET kode_unit = '401432' WHERE nama_unit = 'Pengadilan Agama Pasuruan';
UPDATE unit_kerja SET kode_unit = '400967' WHERE nama_unit = 'Pengadilan Agama Pati';
UPDATE unit_kerja SET kode_unit = '402050' WHERE nama_unit = 'Pengadilan Agama Payakumbuh';
UPDATE unit_kerja SET kode_unit = '400860' WHERE nama_unit = 'Pengadilan Agama Pekalongan';
UPDATE unit_kerja SET kode_unit = '402072' WHERE nama_unit = 'Pengadilan Agama Pekanbaru';
UPDATE unit_kerja SET kode_unit = '307115' WHERE nama_unit = 'Pengadilan Agama Pelaihari';
UPDATE unit_kerja SET kode_unit = '400879' WHERE nama_unit = 'Pengadilan Agama Pemalang';
UPDATE unit_kerja SET kode_unit = '401859' WHERE nama_unit = 'Pengadilan Agama Pematang Siantar';
UPDATE unit_kerja SET kode_unit = '401877' WHERE nama_unit = 'Pengadilan Agama Penajam';
UPDATE unit_kerja SET kode_unit = '307580' WHERE nama_unit = 'Pengadilan Agama Pinrang';
UPDATE unit_kerja SET kode_unit = '307630' WHERE nama_unit = 'Pengadilan Agama Polewali';
UPDATE unit_kerja SET kode_unit = '401514' WHERE nama_unit = 'Pengadilan Agama Ponorogo';
UPDATE unit_kerja SET kode_unit = '402361' WHERE nama_unit = 'Pengadilan Agama Pontianak';
UPDATE unit_kerja SET kode_unit = '307292' WHERE nama_unit = 'Pengadilan Agama Poso';
UPDATE unit_kerja SET kode_unit = '401949' WHERE nama_unit = 'Pengadilan Agama Prabumulih';
UPDATE unit_kerja SET kode_unit = '307907' WHERE nama_unit = 'Pengadilan Agama Praya';
UPDATE unit_kerja SET kode_unit = '401951' WHERE nama_unit = 'Pengadilan Agama Pringsewu';
UPDATE unit_kerja SET kode_unit = '401457' WHERE nama_unit = 'Pengadilan Agama Probolinggo';
UPDATE unit_kerja SET kode_unit = '401875' WHERE nama_unit = 'Pengadilan Agama Pulang Pisau';
UPDATE unit_kerja SET kode_unit = '401936' WHERE nama_unit = 'Pengadilan Agama Pulau Punjung';
UPDATE unit_kerja SET kode_unit = '401092' WHERE nama_unit = 'Pengadilan Agama Purbalingga';
UPDATE unit_kerja SET kode_unit = '400854' WHERE nama_unit = 'Pengadilan Agama Purwakarta';
UPDATE unit_kerja SET kode_unit = '400951' WHERE nama_unit = 'Pengadilan Agama Purwodadi';
UPDATE unit_kerja SET kode_unit = '401061' WHERE nama_unit = 'Pengadilan Agama Purwokerto';
UPDATE unit_kerja SET kode_unit = '401049' WHERE nama_unit = 'Pengadilan Agama Purworejo';
UPDATE unit_kerja SET kode_unit = '402412' WHERE nama_unit = 'Pengadilan Agama Putusibau';
UPDATE unit_kerja SET kode_unit = '307708' WHERE nama_unit = 'Pengadilan Agama Raha';
UPDATE unit_kerja SET kode_unit = '400817' WHERE nama_unit = 'Pengadilan Agama Rangkasbitung';
UPDATE unit_kerja SET kode_unit = '402525' WHERE nama_unit = 'Pengadilan Agama Rantau';
UPDATE unit_kerja SET kode_unit = '401812' WHERE nama_unit = 'Pengadilan Agama Rantau Prapat';
UPDATE unit_kerja SET kode_unit = '400998' WHERE nama_unit = 'Pengadilan Agama Rembang';
UPDATE unit_kerja SET kode_unit = '402081' WHERE nama_unit = 'Pengadilan Agama Rengat';
UPDATE unit_kerja SET kode_unit = '401887' WHERE nama_unit = 'Pengadilan Agama Rumbia';
UPDATE unit_kerja SET kode_unit = '402808' WHERE nama_unit = 'Pengadilan Agama Ruteng';
UPDATE unit_kerja SET kode_unit = '400920' WHERE nama_unit = 'Pengadilan Agama Salatiga';
UPDATE unit_kerja SET kode_unit = '307178' WHERE nama_unit = 'Pengadilan Agama Samarinda';
UPDATE unit_kerja SET kode_unit = '402370' WHERE nama_unit = 'Pengadilan Agama Sambas';
UPDATE unit_kerja SET kode_unit = '401551' WHERE nama_unit = 'Pengadilan Agama Sampang';
UPDATE unit_kerja SET kode_unit = '402474' WHERE nama_unit = 'Pengadilan Agama Sampit';
UPDATE unit_kerja SET kode_unit = '652097' WHERE nama_unit = 'Pengadilan Agama Sangatta';
UPDATE unit_kerja SET kode_unit = '402392' WHERE nama_unit = 'Pengadilan Agama Sanggau';
UPDATE unit_kerja SET kode_unit = '632018' WHERE nama_unit = 'Pengadilan Agama Sarolangun';
UPDATE unit_kerja SET kode_unit = '401931' WHERE nama_unit = 'Pengadilan Agama Sawahlunto';
UPDATE unit_kerja SET kode_unit = '401935' WHERE nama_unit = 'Pengadilan Agama Sei Rampah';
UPDATE unit_kerja SET kode_unit = '402638' WHERE nama_unit = 'Pengadilan Agama Sekayu';
UPDATE unit_kerja SET kode_unit = '402132' WHERE nama_unit = 'Pengadilan Agama Selat Panjang';
UPDATE unit_kerja SET kode_unit = '307562' WHERE nama_unit = 'Pengadilan Agama Selayar';
UPDATE unit_kerja SET kode_unit = '307911' WHERE nama_unit = 'Pengadilan Agama Selong';
UPDATE unit_kerja SET kode_unit = '400911' WHERE nama_unit = 'Pengadilan Agama Semarang';
UPDATE unit_kerja SET kode_unit = '401878' WHERE nama_unit = 'Pengadilan Agama Sendawar';
UPDATE unit_kerja SET kode_unit = '652034' WHERE nama_unit = 'Pengadilan Agama Sengeti';
UPDATE unit_kerja SET kode_unit = '307513' WHERE nama_unit = 'Pengadilan Agama Sengkang';
UPDATE unit_kerja SET kode_unit = '614769' WHERE nama_unit = 'Pengadilan Agama Sentani';
UPDATE unit_kerja SET kode_unit = '400797' WHERE nama_unit = 'Pengadilan Agama Serang';
UPDATE unit_kerja SET kode_unit = '402942' WHERE nama_unit = 'Pengadilan Agama Serui';
UPDATE unit_kerja SET kode_unit = '401937' WHERE nama_unit = 'Pengadilan Agama Siak Sri Indrapura';
UPDATE unit_kerja SET kode_unit = '401871' WHERE nama_unit = 'Pengadilan Agama Sibolga';
UPDATE unit_kerja SET kode_unit = '401934' WHERE nama_unit = 'Pengadilan Agama Sibuhuan';
UPDATE unit_kerja SET kode_unit = '307602' WHERE nama_unit = 'Pengadilan Agama Sidenreng Rappang';
UPDATE unit_kerja SET kode_unit = '401840' WHERE nama_unit = 'Pengadilan Agama Sidikalang';
UPDATE unit_kerja SET kode_unit = '401262' WHERE nama_unit = 'Pengadilan Agama Sidoarjo';
UPDATE unit_kerja SET kode_unit = '401978' WHERE nama_unit = 'Pengadilan Agama Sijunjung';
UPDATE unit_kerja SET kode_unit = '403083' WHERE nama_unit = 'Pengadilan Agama Simalungun';
UPDATE unit_kerja SET kode_unit = '307839' WHERE nama_unit = 'Pengadilan Agama Singaraja';
UPDATE unit_kerja SET kode_unit = '401960' WHERE nama_unit = 'Pengadilan Agama Singkawang';
UPDATE unit_kerja SET kode_unit = '307555' WHERE nama_unit = 'Pengadilan Agama Sinjai';
UPDATE unit_kerja SET kode_unit = '402406' WHERE nama_unit = 'Pengadilan Agama Sintang';
UPDATE unit_kerja SET kode_unit = '401350' WHERE nama_unit = 'Pengadilan Agama Situbondo';
UPDATE unit_kerja SET kode_unit = '403015' WHERE nama_unit = 'Pengadilan Agama Slawi';
UPDATE unit_kerja SET kode_unit = '401200' WHERE nama_unit = 'Pengadilan Agama Sleman';
UPDATE unit_kerja SET kode_unit = '307801' WHERE nama_unit = 'Pengadilan Agama Soa';
UPDATE unit_kerja SET kode_unit = '402820' WHERE nama_unit = 'Pengadilan Agama Soe';
UPDATE unit_kerja SET kode_unit = '401922' WHERE nama_unit = 'Pengadilan Agama Solok';
UPDATE unit_kerja SET kode_unit = '401957' WHERE nama_unit = 'Pengadilan Agama Soreang';
UPDATE unit_kerja SET kode_unit = '402882' WHERE nama_unit = 'Pengadilan Agama Sorong';
UPDATE unit_kerja SET kode_unit = '401143' WHERE nama_unit = 'Pengadilan Agama Sragen';
UPDATE unit_kerja SET kode_unit = '547682' WHERE nama_unit = 'Pengadilan Agama Stabat';
UPDATE unit_kerja SET kode_unit = '402587' WHERE nama_unit = 'Pengadilan Agama Subang';
UPDATE unit_kerja SET kode_unit = '400735' WHERE nama_unit = 'Pengadilan Agama Sukabumi';
UPDATE unit_kerja SET kode_unit = '401956' WHERE nama_unit = 'Pengadilan Agama Sukadana';
UPDATE unit_kerja SET kode_unit = '401869' WHERE nama_unit = 'Pengadilan Agama Sukamara';
UPDATE unit_kerja SET kode_unit = '401168' WHERE nama_unit = 'Pengadilan Agama Sukoharjo';
UPDATE unit_kerja SET kode_unit = '307892' WHERE nama_unit = 'Pengadilan Agama Sumbawa Besar';
UPDATE unit_kerja SET kode_unit = '403009' WHERE nama_unit = 'Pengadilan Agama Sumber';
UPDATE unit_kerja SET kode_unit = '400678' WHERE nama_unit = 'Pengadilan Agama Sumedang';
UPDATE unit_kerja SET kode_unit = '401560' WHERE nama_unit = 'Pengadilan Agama Sumenep';
UPDATE unit_kerja SET kode_unit = '402220' WHERE nama_unit = 'Pengadilan Agama Sungai Penuh';
UPDATE unit_kerja SET kode_unit = '401964' WHERE nama_unit = 'Pengadilan Agama Sungai Raya';
UPDATE unit_kerja SET kode_unit = '403092' WHERE nama_unit = 'Pengadilan Agama Sungailiat';
UPDATE unit_kerja SET kode_unit = '307491' WHERE nama_unit = 'Pengadilan Agama Sungguminasa';
UPDATE unit_kerja SET kode_unit = '401240' WHERE nama_unit = 'Pengadilan Agama Surabaya';
UPDATE unit_kerja SET kode_unit = '401180' WHERE nama_unit = 'Pengadilan Agama Surakarta';
UPDATE unit_kerja SET kode_unit = '401892' WHERE nama_unit = 'Pengadilan Agama Suwawa';
UPDATE unit_kerja SET kode_unit = '402757' WHERE nama_unit = 'Pengadilan Agama Tabanan';
UPDATE unit_kerja SET kode_unit = '307246' WHERE nama_unit = 'Pengadilan Agama Tahuna';
UPDATE unit_kerja SET kode_unit = '401941' WHERE nama_unit = 'Pengadilan Agama Tais';
UPDATE unit_kerja SET kode_unit = '307470' WHERE nama_unit = 'Pengadilan Agama Takalar';
UPDATE unit_kerja SET kode_unit = '682274' WHERE nama_unit = 'Pengadilan Agama Taliwang';
UPDATE unit_kerja SET kode_unit = '402035' WHERE nama_unit = 'Pengadilan Agama Talu';
UPDATE unit_kerja SET kode_unit = '401874' WHERE nama_unit = 'Pengadilan Agama Tamiyang Layang';
UPDATE unit_kerja SET kode_unit = '307182' WHERE nama_unit = 'Pengadilan Agama Tanah Grogot';
UPDATE unit_kerja SET kode_unit = '400823' WHERE nama_unit = 'Pengadilan Agama Tangerang';
UPDATE unit_kerja SET kode_unit = '614691' WHERE nama_unit = 'Pengadilan Agama Tanggamus';
UPDATE unit_kerja SET kode_unit = '402562' WHERE nama_unit = 'Pengadilan Agama Tanjung';
UPDATE unit_kerja SET kode_unit = '401828' WHERE nama_unit = 'Pengadilan Agama Tanjung Balai';
UPDATE unit_kerja SET kode_unit = '402160' WHERE nama_unit = 'Pengadilan Agama Tanjung Balai Karimun';
UPDATE unit_kerja SET kode_unit = '402318' WHERE nama_unit = 'Pengadilan Agama Tanjung Pandan';
UPDATE unit_kerja SET kode_unit = '402066' WHERE nama_unit = 'Pengadilan Agama Tanjung Pati';
UPDATE unit_kerja SET kode_unit = '402148' WHERE nama_unit = 'Pengadilan Agama Tanjung Pinang';
UPDATE unit_kerja SET kode_unit = '307204' WHERE nama_unit = 'Pengadilan Agama Tanjung Redep';
UPDATE unit_kerja SET kode_unit = '417657' WHERE nama_unit = 'Pengadilan Agama Tanjung Selor';
UPDATE unit_kerja SET kode_unit = '402324' WHERE nama_unit = 'Pengadilan Agama Tanjungkarang';
UPDATE unit_kerja SET kode_unit = '402675' WHERE nama_unit = 'Pengadilan Agama Tarakan';
UPDATE unit_kerja SET kode_unit = '402179' WHERE nama_unit = 'Pengadilan Agama Tarempa';
UPDATE unit_kerja SET kode_unit = '631978' WHERE nama_unit = 'Pengadilan Agama Tarutung';
UPDATE unit_kerja SET kode_unit = '400704' WHERE nama_unit = 'Pengadilan Agama Tasikmalaya';
UPDATE unit_kerja SET kode_unit = '401834' WHERE nama_unit = 'Pengadilan Agama Tebing Tinggi';
UPDATE unit_kerja SET kode_unit = '400885' WHERE nama_unit = 'Pengadilan Agama Tegal';
UPDATE unit_kerja SET kode_unit = '401938' WHERE nama_unit = 'Pengadilan Agama Teluk Kuantan';
UPDATE unit_kerja SET kode_unit = '401024' WHERE nama_unit = 'Pengadilan Agama Temanggung';
UPDATE unit_kerja SET kode_unit = '402097' WHERE nama_unit = 'Pengadilan Agama Tembilahan';
UPDATE unit_kerja SET kode_unit = '307161' WHERE nama_unit = 'Pengadilan Agama Tenggarong';
UPDATE unit_kerja SET kode_unit = '307782' WHERE nama_unit = 'Pengadilan Agama Ternate';
UPDATE unit_kerja SET kode_unit = '604723' WHERE nama_unit = 'Pengadilan Agama Tigaraksa';
UPDATE unit_kerja SET kode_unit = '652130' WHERE nama_unit = 'Pengadilan Agama Tilamuta';
UPDATE unit_kerja SET kode_unit = '307288' WHERE nama_unit = 'Pengadilan Agama Toli';
UPDATE unit_kerja SET kode_unit = '402701' WHERE nama_unit = 'Pengadilan Agama Tondano';
UPDATE unit_kerja SET kode_unit = '401390' WHERE nama_unit = 'Pengadilan Agama Trenggalek';
UPDATE unit_kerja SET kode_unit = '307761' WHERE nama_unit = 'Pengadilan Agama Tual';
UPDATE unit_kerja SET kode_unit = '450737' WHERE nama_unit = 'Pengadilan Agama Tuban';
UPDATE unit_kerja SET kode_unit = '614684' WHERE nama_unit = 'Pengadilan Agama Tulang Bawang';
UPDATE unit_kerja SET kode_unit = '401955' WHERE nama_unit = 'Pengadilan Agama Tulang Bawang Tengah';
UPDATE unit_kerja SET kode_unit = '401381' WHERE nama_unit = 'Pengadilan Agama Tulungagung';
UPDATE unit_kerja SET kode_unit = '401891' WHERE nama_unit = 'Pengadilan Agama Tutuyan';
UPDATE unit_kerja SET kode_unit = '632001' WHERE nama_unit = 'Pengadilan Agama Ujung Tanjung';
UPDATE unit_kerja SET kode_unit = '604772' WHERE nama_unit = 'Pengadilan Agama Unaaha';
UPDATE unit_kerja SET kode_unit = '307949' WHERE nama_unit = 'Pengadilan Agama Waikabubak';
UPDATE unit_kerja SET kode_unit = '307981' WHERE nama_unit = 'Pengadilan Agama Waingapu';
UPDATE unit_kerja SET kode_unit = '402933' WHERE nama_unit = 'Pengadilan Agama Wamena';
UPDATE unit_kerja SET kode_unit = '401885' WHERE nama_unit = 'Pengadilan Agama Wangi Wangi';
UPDATE unit_kerja SET kode_unit = '307509' WHERE nama_unit = 'Pengadilan Agama Watampone';
UPDATE unit_kerja SET kode_unit = '307520' WHERE nama_unit = 'Pengadilan Agama Watansoppeng';
UPDATE unit_kerja SET kode_unit = '401219' WHERE nama_unit = 'Pengadilan Agama Wates';
UPDATE unit_kerja SET kode_unit = '401152' WHERE nama_unit = 'Pengadilan Agama Wonogiri';
UPDATE unit_kerja SET kode_unit = '401231' WHERE nama_unit = 'Pengadilan Agama Wonosari';
UPDATE unit_kerja SET kode_unit = '401030' WHERE nama_unit = 'Pengadilan Agama Wonosobo';
UPDATE unit_kerja SET kode_unit = '401199' WHERE nama_unit = 'Pengadilan Agama Yogyakarta';
UPDATE unit_kerja SET kode_unit = '402710' WHERE nama_unit = 'Pengadilan Tinggi Agama Ambon';
UPDATE unit_kerja SET kode_unit = '526724' WHERE nama_unit = 'Pengadilan Tinggi Agama Bali';
UPDATE unit_kerja SET kode_unit = '547678' WHERE nama_unit = 'Pengadilan Tinggi Agama Bandar Lampung';
UPDATE unit_kerja SET kode_unit = '308166' WHERE nama_unit = 'Pengadilan Tinggi Agama Bandung';
UPDATE unit_kerja SET kode_unit = '440728' WHERE nama_unit = 'Pengadilan Tinggi Agama Bangka Belitung';
UPDATE unit_kerja SET kode_unit = '402449' WHERE nama_unit = 'Pengadilan Tinggi Agama Banjarmasin';
UPDATE unit_kerja SET kode_unit = '440712' WHERE nama_unit = 'Pengadilan Tinggi Agama Banten';
UPDATE unit_kerja SET kode_unit = '576274' WHERE nama_unit = 'Pengadilan Tinggi Agama Bengkulu';
UPDATE unit_kerja SET kode_unit = '440734' WHERE nama_unit = 'Pengadilan Tinggi Agama Gorontalo';
UPDATE unit_kerja SET kode_unit = '401112' WHERE nama_unit = 'Pengadilan Tinggi Agama Jakarta';
UPDATE unit_kerja SET kode_unit = '547661' WHERE nama_unit = 'Pengadilan Tinggi Agama Jambi';
UPDATE unit_kerja SET kode_unit = '402860' WHERE nama_unit = 'Pengadilan Tinggi Agama Jayapura';
UPDATE unit_kerja SET kode_unit = '526722' WHERE nama_unit = 'Pengadilan Tinggi Agama Kalimantan Utara';
UPDATE unit_kerja SET kode_unit = '576253' WHERE nama_unit = 'Pengadilan Tinggi Agama Kendari';
UPDATE unit_kerja SET kode_unit = '526708' WHERE nama_unit = 'Pengadilan Tinggi Agama Kepulauan Riau';
UPDATE unit_kerja SET kode_unit = '576260' WHERE nama_unit = 'Pengadilan Tinggi Agama Kupang';
UPDATE unit_kerja SET kode_unit = '307424' WHERE nama_unit = 'Pengadilan Tinggi Agama Makassar';
UPDATE unit_kerja SET kode_unit = '440740' WHERE nama_unit = 'Pengadilan Tinggi Agama Maluku Utara';
UPDATE unit_kerja SET kode_unit = '402681' WHERE nama_unit = 'Pengadilan Tinggi Agama Manado';
UPDATE unit_kerja SET kode_unit = '402788' WHERE nama_unit = 'Pengadilan Tinggi Agama Mataram';
UPDATE unit_kerja SET kode_unit = '401777' WHERE nama_unit = 'Pengadilan Tinggi Agama Medan';
UPDATE unit_kerja SET kode_unit = '401900' WHERE nama_unit = 'Pengadilan Tinggi Agama Padang';
UPDATE unit_kerja SET kode_unit = '402989' WHERE nama_unit = 'Pengadilan Tinggi Agama Palangkaraya';
UPDATE unit_kerja SET kode_unit = '402236' WHERE nama_unit = 'Pengadilan Tinggi Agama Palembang';
UPDATE unit_kerja SET kode_unit = '576249' WHERE nama_unit = 'Pengadilan Tinggi Agama Palu';
UPDATE unit_kerja SET kode_unit = '526718' WHERE nama_unit = 'Pengadilan Tinggi Agama Papua Barat';
UPDATE unit_kerja SET kode_unit = '402970' WHERE nama_unit = 'Pengadilan Tinggi Agama Pekanbaru';
UPDATE unit_kerja SET kode_unit = '402650' WHERE nama_unit = 'Pengadilan Tinggi Agama Pontianak';
UPDATE unit_kerja SET kode_unit = '402480' WHERE nama_unit = 'Pengadilan Tinggi Agama Samarinda';
UPDATE unit_kerja SET kode_unit = '402964' WHERE nama_unit = 'Pengadilan Tinggi Agama Semarang';
UPDATE unit_kerja SET kode_unit = '526714' WHERE nama_unit = 'Pengadilan Tinggi Agama Sulawesi Barat';
UPDATE unit_kerja SET kode_unit = '308170' WHERE nama_unit = 'Pengadilan Tinggi Agama Surabaya';
UPDATE unit_kerja SET kode_unit = '547657' WHERE nama_unit = 'Pengadilan Tinggi Agama Yogyakarta';
UPDATE unit_kerja SET kode_unit = '663182' WHERE nama_unit = 'PENGADILAN MILITER I - 01 BANDA ACEH';
UPDATE unit_kerja SET kode_unit = '663199' WHERE nama_unit = 'PENGADILAN MILITER I - 02 MEDAN';
UPDATE unit_kerja SET kode_unit = '663204' WHERE nama_unit = 'PENGADILAN MILITER I - 03 PADANG';
UPDATE unit_kerja SET kode_unit = '663211' WHERE nama_unit = 'PENGADILAN MILITER I - 04 PALEMBANG';
UPDATE unit_kerja SET kode_unit = '663225' WHERE nama_unit = 'PENGADILAN MILITER I - 05 PONTIANAK';
UPDATE unit_kerja SET kode_unit = '663232' WHERE nama_unit = 'PENGADILAN MILITER I - 06 BANJARMASIN';
UPDATE unit_kerja SET kode_unit = '663246' WHERE nama_unit = 'PENGADILAN MILITER I - 07 BALIKPAPAN';
UPDATE unit_kerja SET kode_unit = '663267' WHERE nama_unit = 'PENGADILAN MILITER II - 08 JAKARTA';
UPDATE unit_kerja SET kode_unit = '663271' WHERE nama_unit = 'PENGADILAN MILITER II - 09 BANDUNG';
UPDATE unit_kerja SET kode_unit = '663288' WHERE nama_unit = 'PENGADILAN MILITER II - 10 SEMARANG';
UPDATE unit_kerja SET kode_unit = '663292' WHERE nama_unit = 'PENGADILAN MILITER II - 11 YOGYAKARTA';
UPDATE unit_kerja SET kode_unit = '663314' WHERE nama_unit = 'PENGADILAN MILITER III - 12 SURABAYA';
UPDATE unit_kerja SET kode_unit = '663321' WHERE nama_unit = 'PENGADILAN MILITER III - 13 MADIUN';
UPDATE unit_kerja SET kode_unit = '663335' WHERE nama_unit = 'PENGADILAN MILITER III - 14 DENPASAR';
UPDATE unit_kerja SET kode_unit = '663342' WHERE nama_unit = 'PENGADILAN MILITER III - 15 KUPANG';
UPDATE unit_kerja SET kode_unit = '663356' WHERE nama_unit = 'PENGADILAN MILITER III - 16 MAKASSAR';
UPDATE unit_kerja SET kode_unit = '663360' WHERE nama_unit = 'PENGADILAN MILITER III - 17 MANADO';
UPDATE unit_kerja SET kode_unit = '663377' WHERE nama_unit = 'PENGADILAN MILITER III - 18 AMBON';
UPDATE unit_kerja SET kode_unit = '663381' WHERE nama_unit = 'PENGADILAN MILITER III - 19 JAYAPURA';
UPDATE unit_kerja SET kode_unit = '663178' WHERE nama_unit = 'PENGADILAN MILITER TINGGI I MEDAN';
UPDATE unit_kerja SET kode_unit = '663250' WHERE nama_unit = 'PENGADILAN MILITER TINGGI II JAKARTA';
UPDATE unit_kerja SET kode_unit = '663300' WHERE nama_unit = 'PENGADILAN MILITER TINGGI III SURABAYA';
UPDATE unit_kerja SET kode_unit = '663161' WHERE nama_unit = 'PENGADILAN MILITER UTAMA';
UPDATE unit_kerja SET kode_unit = '578818' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Aceh';
UPDATE unit_kerja SET kode_unit = '539117' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Ambon';
UPDATE unit_kerja SET kode_unit = '559840' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Bandar Lampung';
UPDATE unit_kerja SET kode_unit = '531823' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Bandung';
UPDATE unit_kerja SET kode_unit = '531865' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Banjarmasin';
UPDATE unit_kerja SET kode_unit = '578885' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Bengkulu';
UPDATE unit_kerja SET kode_unit = '559861' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Denpasar';
UPDATE unit_kerja SET kode_unit = '401969' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Gorontalo';
UPDATE unit_kerja SET kode_unit = '526732' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Jakarta';
UPDATE unit_kerja SET kode_unit = '578839' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Jambi';
UPDATE unit_kerja SET kode_unit = '539138' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Jayapura';
UPDATE unit_kerja SET kode_unit = '578864' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Kendari';
UPDATE unit_kerja SET kode_unit = '539121' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Kupang';
UPDATE unit_kerja SET kode_unit = '526771' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Makassar';
UPDATE unit_kerja SET kode_unit = '531872' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Manado';
UPDATE unit_kerja SET kode_unit = '578871' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Mataram';
UPDATE unit_kerja SET kode_unit = '526746' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Medan';
UPDATE unit_kerja SET kode_unit = '531844' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Padang';
UPDATE unit_kerja SET kode_unit = '578843' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Palangkaraya';
UPDATE unit_kerja SET kode_unit = '526750' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Palembang';
UPDATE unit_kerja SET kode_unit = '578850' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Palu';
UPDATE unit_kerja SET kode_unit = '401968' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Pangkal Pinang';
UPDATE unit_kerja SET kode_unit = '578822' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Pekanbaru';
UPDATE unit_kerja SET kode_unit = '531851' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Pontianak';
UPDATE unit_kerja SET kode_unit = '559857' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Samarinda';
UPDATE unit_kerja SET kode_unit = '531830' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Semarang';
UPDATE unit_kerja SET kode_unit = '689313' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Serang';
UPDATE unit_kerja SET kode_unit = '526767' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Surabaya';
UPDATE unit_kerja SET kode_unit = '689309' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Tanjung Pinang';
UPDATE unit_kerja SET kode_unit = '578801' WHERE nama_unit = 'Pengadilan Tata Usaha Negara Yogyakarta';
UPDATE unit_kerja SET kode_unit = '526730' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Banjarmasin';
UPDATE unit_kerja SET kode_unit = '526704' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Jakarta';
UPDATE unit_kerja SET kode_unit = '526711' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Makassar';
UPDATE unit_kerja SET kode_unit = '526734' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Manado';
UPDATE unit_kerja SET kode_unit = '526736' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Mataram';
UPDATE unit_kerja SET kode_unit = '526725' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Medan';
UPDATE unit_kerja SET kode_unit = '526728' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Palembang';
UPDATE unit_kerja SET kode_unit = '548940' WHERE nama_unit = 'Pengadilan Tinggi Tata Usaha Negara Surabaya';
UPDATE unit_kerja SET kode_unit = '670210' WHERE nama_unit = 'Pengadilan Negeri Airmadidi';
UPDATE unit_kerja SET kode_unit = '099706' WHERE nama_unit = 'Pengadilan Negeri Ambon';
UPDATE unit_kerja SET kode_unit = '099837' WHERE nama_unit = 'Pengadilan Negeri Amlapura';
UPDATE unit_kerja SET kode_unit = '099251' WHERE nama_unit = 'Pengadilan Negeri Amuntai';
UPDATE unit_kerja SET kode_unit = '673034' WHERE nama_unit = 'Pengadilan Negeri Amurang';
UPDATE unit_kerja SET kode_unit = '681439' WHERE nama_unit = 'Pengadilan Negeri Andoolo';
UPDATE unit_kerja SET kode_unit = '400239' WHERE nama_unit = 'Pengadilan Negeri Arga Makmur';
UPDATE unit_kerja SET kode_unit = '099930' WHERE nama_unit = 'Pengadilan Negeri Atambua';
UPDATE unit_kerja SET kode_unit = '400157' WHERE nama_unit = 'Pengadilan Negeri Bajawa';
UPDATE unit_kerja SET kode_unit = '400483' WHERE nama_unit = 'Pengadilan Negeri Bale Bandung';
UPDATE unit_kerja SET kode_unit = '672910' WHERE nama_unit = 'Pengadilan Negeri Balige';
UPDATE unit_kerja SET kode_unit = '099308' WHERE nama_unit = 'Pengadilan Negeri Balikpapan';
UPDATE unit_kerja SET kode_unit = '098441' WHERE nama_unit = 'Pengadilan Negeri Banda Aceh';
UPDATE unit_kerja SET kode_unit = '097514' WHERE nama_unit = 'Pengadilan Negeri Bandung';
UPDATE unit_kerja SET kode_unit = '098324' WHERE nama_unit = 'Pengadilan Negeri Bangil';
UPDATE unit_kerja SET kode_unit = '098413' WHERE nama_unit = 'Pengadilan Negeri Bangkalan';
UPDATE unit_kerja SET kode_unit = '400141' WHERE nama_unit = 'Pengadilan Negeri Bangkinang';
UPDATE unit_kerja SET kode_unit = '400311' WHERE nama_unit = 'Pengadilan Negeri Bangko';
UPDATE unit_kerja SET kode_unit = '099858' WHERE nama_unit = 'Pengadilan Negeri Bangli';
UPDATE unit_kerja SET kode_unit = '401914' WHERE nama_unit = 'Pengadilan Negeri Banjar';
UPDATE unit_kerja SET kode_unit = '653458' WHERE nama_unit = 'Pengadilan Negeri Banjarbaru';
UPDATE unit_kerja SET kode_unit = '099197' WHERE nama_unit = 'Pengadilan Negeri Banjarmasin';
UPDATE unit_kerja SET kode_unit = '098040' WHERE nama_unit = 'Pengadilan Negeri Banjarnegara';
UPDATE unit_kerja SET kode_unit = '099560' WHERE nama_unit = 'Pengadilan Negeri Bantaeng';
UPDATE unit_kerja SET kode_unit = '400172' WHERE nama_unit = 'Pengadilan Negeri Bantul';
UPDATE unit_kerja SET kode_unit = '098022' WHERE nama_unit = 'Pengadilan Negeri Banyumas';
UPDATE unit_kerja SET kode_unit = '098214' WHERE nama_unit = 'Pengadilan Negeri Banyuwangi';
UPDATE unit_kerja SET kode_unit = '099223' WHERE nama_unit = 'Pengadilan Negeri Barabai';
UPDATE unit_kerja SET kode_unit = '099450' WHERE nama_unit = 'Pengadilan Negeri Barru';
UPDATE unit_kerja SET kode_unit = '108309' WHERE nama_unit = 'Pengadilan Negeri Batam';
UPDATE unit_kerja SET kode_unit = '097872' WHERE nama_unit = 'Pengadilan Negeri Batang';
UPDATE unit_kerja SET kode_unit = '670206' WHERE nama_unit = 'Pengadilan Negeri Batu Licin';
UPDATE unit_kerja SET kode_unit = '098963' WHERE nama_unit = 'Pengadilan Negeri Baturaja';
UPDATE unit_kerja SET kode_unit = '098771' WHERE nama_unit = 'Pengadilan Negeri Batusangkar';
UPDATE unit_kerja SET kode_unit = '099663' WHERE nama_unit = 'Pengadilan Negeri Bau';
UPDATE unit_kerja SET kode_unit = '097610' WHERE nama_unit = 'Pengadilan Negeri Bekasi';
UPDATE unit_kerja SET kode_unit = '401928' WHERE nama_unit = 'Pengadilan Negeri Belopa';
UPDATE unit_kerja SET kode_unit = '098853' WHERE nama_unit = 'Pengadilan Negeri Bengkalis';
UPDATE unit_kerja SET kode_unit = '670231' WHERE nama_unit = 'Pengadilan Negeri Bengkayang';
UPDATE unit_kerja SET kode_unit = '400110' WHERE nama_unit = 'Pengadilan Negeri Bengkulu';
UPDATE unit_kerja SET kode_unit = '400090' WHERE nama_unit = 'Pengadilan Negeri Biak';
UPDATE unit_kerja SET kode_unit = '098633' WHERE nama_unit = 'Pengadilan Negeri Binjai';
UPDATE unit_kerja SET kode_unit = '672994' WHERE nama_unit = 'Pengadilan Negeri Bintuhan';
UPDATE unit_kerja SET kode_unit = '098476' WHERE nama_unit = 'Pengadilan Negeri Bireuen';
UPDATE unit_kerja SET kode_unit = '568725' WHERE nama_unit = 'Pengadilan Negeri Bitung';
UPDATE unit_kerja SET kode_unit = '663051' WHERE nama_unit = 'Pengadilan Negeri Blambangan Umpu';
UPDATE unit_kerja SET kode_unit = '098544' WHERE nama_unit = 'Pengadilan Negeri Blangkajeren';
UPDATE unit_kerja SET kode_unit = '401902' WHERE nama_unit = 'Pengadilan Negeri Blangpidie';
UPDATE unit_kerja SET kode_unit = '098277' WHERE nama_unit = 'Pengadilan Negeri Blitar';
UPDATE unit_kerja SET kode_unit = '097851' WHERE nama_unit = 'Pengadilan Negeri Blora';
UPDATE unit_kerja SET kode_unit = '401973' WHERE nama_unit = 'Pengadilan Negeri Bobong';
UPDATE unit_kerja SET kode_unit = '097645' WHERE nama_unit = 'Pengadilan Negeri Bogor';
UPDATE unit_kerja SET kode_unit = '098125' WHERE nama_unit = 'Pengadilan Negeri Bojonegoro';
UPDATE unit_kerja SET kode_unit = '098192' WHERE nama_unit = 'Pengadilan Negeri Bondowoso';
UPDATE unit_kerja SET kode_unit = '662972' WHERE nama_unit = 'Pengadilan Negeri Bontang';
UPDATE unit_kerja SET kode_unit = '097982' WHERE nama_unit = 'Pengadilan Negeri Boyolali';
UPDATE unit_kerja SET kode_unit = '097776' WHERE nama_unit = 'Pengadilan Negeri Brebes';
UPDATE unit_kerja SET kode_unit = '098811' WHERE nama_unit = 'Pengadilan Negeri Bukittinggi';
UPDATE unit_kerja SET kode_unit = '099581' WHERE nama_unit = 'Pengadilan Negeri Bulukumba';
UPDATE unit_kerja SET kode_unit = '099162' WHERE nama_unit = 'Pengadilan Negeri Buntok';
UPDATE unit_kerja SET kode_unit = '670248' WHERE nama_unit = 'Pengadilan Negeri Buol';
UPDATE unit_kerja SET kode_unit = '098572' WHERE nama_unit = 'Pengadilan Negeri Calang';
UPDATE unit_kerja SET kode_unit = '097556' WHERE nama_unit = 'Pengadilan Negeri Ciamis';
UPDATE unit_kerja SET kode_unit = '097666' WHERE nama_unit = 'Pengadilan Negeri Cianjur';
UPDATE unit_kerja SET kode_unit = '400409' WHERE nama_unit = 'Pengadilan Negeri Cibadak';
UPDATE unit_kerja SET kode_unit = '613519' WHERE nama_unit = 'Pengadilan Negeri Cibinong';
UPDATE unit_kerja SET kode_unit = '401915' WHERE nama_unit = 'Pengadilan Negeri Cikarang';
UPDATE unit_kerja SET kode_unit = '098015' WHERE nama_unit = 'Pengadilan Negeri Cilacap';
UPDATE unit_kerja SET kode_unit = '097670' WHERE nama_unit = 'Pengadilan Negeri Cirebon';
UPDATE unit_kerja SET kode_unit = '400126' WHERE nama_unit = 'Pengadilan Negeri Curup';
UPDATE unit_kerja SET kode_unit = '401971' WHERE nama_unit = 'Pengadilan Negeri Dataran Hunimoa';
UPDATE unit_kerja SET kode_unit = '401970' WHERE nama_unit = 'Pengadilan Negeri Dataran Hunipopu';
UPDATE unit_kerja SET kode_unit = '097802' WHERE nama_unit = 'Pengadilan Negeri Demak';
UPDATE unit_kerja SET kode_unit = '099780' WHERE nama_unit = 'Pengadilan Negeri Denpasar';
UPDATE unit_kerja SET kode_unit = '477292' WHERE nama_unit = 'Pengadilan Negeri Depok';
UPDATE unit_kerja SET kode_unit = '401929' WHERE nama_unit = 'Pengadilan Negeri Dobo';
UPDATE unit_kerja SET kode_unit = '099905' WHERE nama_unit = 'Pengadilan Negeri Dompu';
UPDATE unit_kerja SET kode_unit = '477202' WHERE nama_unit = 'Pengadilan Negeri Donggala';
UPDATE unit_kerja SET kode_unit = '400327' WHERE nama_unit = 'Pengadilan Negeri Dumai';
UPDATE unit_kerja SET kode_unit = '099989' WHERE nama_unit = 'Pengadilan Negeri Ende';
UPDATE unit_kerja SET kode_unit = '099507' WHERE nama_unit = 'Pengadilan Negeri Enrekang';
UPDATE unit_kerja SET kode_unit = '400081' WHERE nama_unit = 'Pengadilan Negeri Fak';
UPDATE unit_kerja SET kode_unit = '097542' WHERE nama_unit = 'Pengadilan Negeri Garut';
UPDATE unit_kerja SET kode_unit = '401911' WHERE nama_unit = 'Pengadilan Negeri Gedong Tataan';
UPDATE unit_kerja SET kode_unit = '099841' WHERE nama_unit = 'Pengadilan Negeri Gianyar';
UPDATE unit_kerja SET kode_unit = '099361' WHERE nama_unit = 'Pengadilan Negeri Gorontalo';
UPDATE unit_kerja SET kode_unit = '098150' WHERE nama_unit = 'Pengadilan Negeri Gresik';
UPDATE unit_kerja SET kode_unit = '098696' WHERE nama_unit = 'Pengadilan Negeri Gunung Sitoli';
UPDATE unit_kerja SET kode_unit = '663030' WHERE nama_unit = 'Pengadilan Negeri Gunung Sugih';
UPDATE unit_kerja SET kode_unit = '098523' WHERE nama_unit = 'Pengadilan Negeri Idi';
UPDATE unit_kerja SET kode_unit = '097687' WHERE nama_unit = 'Pengadilan Negeri Indramayu';
UPDATE unit_kerja SET kode_unit = '097488' WHERE nama_unit = 'Pengadilan Negeri Jakarta Barat';
UPDATE unit_kerja SET kode_unit = '097471' WHERE nama_unit = 'Pengadilan Negeri Jakarta Pusat';
UPDATE unit_kerja SET kode_unit = '400214' WHERE nama_unit = 'Pengadilan Negeri Jakarta Selatan';
UPDATE unit_kerja SET kode_unit = '097492' WHERE nama_unit = 'Pengadilan Negeri Jakarta Timur';
UPDATE unit_kerja SET kode_unit = '400220' WHERE nama_unit = 'Pengadilan Negeri Jakarta Utara';
UPDATE unit_kerja SET kode_unit = '098895' WHERE nama_unit = 'Pengadilan Negeri Jambi';
UPDATE unit_kerja SET kode_unit = '400415' WHERE nama_unit = 'Pengadilan Negeri Jantho';
UPDATE unit_kerja SET kode_unit = '400038' WHERE nama_unit = 'Pengadilan Negeri Jayapura';
UPDATE unit_kerja SET kode_unit = '098200' WHERE nama_unit = 'Pengadilan Negeri Jember';
UPDATE unit_kerja SET kode_unit = '099485' WHERE nama_unit = 'Pengadilan Negeri Jeneponto';
UPDATE unit_kerja SET kode_unit = '097844' WHERE nama_unit = 'Pengadilan Negeri Jepara';
UPDATE unit_kerja SET kode_unit = '098188' WHERE nama_unit = 'Pengadilan Negeri Jombang';
UPDATE unit_kerja SET kode_unit = '098661' WHERE nama_unit = 'Pengadilan Negeri Kabanjahe';
UPDATE unit_kerja SET kode_unit = '400580' WHERE nama_unit = 'Pengadilan Negeri Kabupaten Kediri';
UPDATE unit_kerja SET kode_unit = '400596' WHERE nama_unit = 'Pengadilan Negeri Kabupaten Madiun';
UPDATE unit_kerja SET kode_unit = '401933' WHERE nama_unit = 'Pengadilan Negeri Kaimana';
UPDATE unit_kerja SET kode_unit = '400163' WHERE nama_unit = 'Pengadilan Negeri Kalabahi';
UPDATE unit_kerja SET kode_unit = '400452' WHERE nama_unit = 'Pengadilan Negeri Kalianda';
UPDATE unit_kerja SET kode_unit = '099202' WHERE nama_unit = 'Pengadilan Negeri Kandangan';
UPDATE unit_kerja SET kode_unit = '097975' WHERE nama_unit = 'Pengadilan Negeri Karanganyar';
UPDATE unit_kerja SET kode_unit = '097624' WHERE nama_unit = 'Pengadilan Negeri Karawang';
UPDATE unit_kerja SET kode_unit = '672973' WHERE nama_unit = 'Pengadilan Negeri Kasongan';
UPDATE unit_kerja SET kode_unit = '098959' WHERE nama_unit = 'Pengadilan Negeri Kayu Agung';
UPDATE unit_kerja SET kode_unit = '097908' WHERE nama_unit = 'Pengadilan Negeri Kebumen';
UPDATE unit_kerja SET kode_unit = '098235' WHERE nama_unit = 'Pengadilan Negeri Kediri';
UPDATE unit_kerja SET kode_unit = '099951' WHERE nama_unit = 'Pengadilan Negeri Kefamenanu';
UPDATE unit_kerja SET kode_unit = '097797' WHERE nama_unit = 'Pengadilan Negeri Kendal';
UPDATE unit_kerja SET kode_unit = '099659' WHERE nama_unit = 'Pengadilan Negeri Kendari';
UPDATE unit_kerja SET kode_unit = '673041' WHERE nama_unit = 'Pengadilan Negeri Kepahiang';
UPDATE unit_kerja SET kode_unit = '626156' WHERE nama_unit = 'Pengadilan Negeri Kepanjen';
UPDATE unit_kerja SET kode_unit = '099091' WHERE nama_unit = 'Pengadilan Negeri Ketapang';
UPDATE unit_kerja SET kode_unit = '400389' WHERE nama_unit = 'Pengadilan Negeri Kisaran';
UPDATE unit_kerja SET kode_unit = '097996' WHERE nama_unit = 'Pengadilan Negeri Klaten';
UPDATE unit_kerja SET kode_unit = '401912' WHERE nama_unit = 'Pengadilan Negeri Koba';
UPDATE unit_kerja SET kode_unit = '099684' WHERE nama_unit = 'Pengadilan Negeri Kolaka';
UPDATE unit_kerja SET kode_unit = '477306' WHERE nama_unit = 'Pengadilan Negeri Kota Agung';
UPDATE unit_kerja SET kode_unit = '098345' WHERE nama_unit = 'Pengadilan Negeri Kota Madiun';
UPDATE unit_kerja SET kode_unit = '099219' WHERE nama_unit = 'Pengadilan Negeri Kotabaru';
UPDATE unit_kerja SET kode_unit = '099052' WHERE nama_unit = 'Pengadilan Negeri Kotabumi';
UPDATE unit_kerja SET kode_unit = '099333' WHERE nama_unit = 'Pengadilan Negeri Kotamobagu';
UPDATE unit_kerja SET kode_unit = '400446' WHERE nama_unit = 'Pengadilan Negeri Koto Baru';
UPDATE unit_kerja SET kode_unit = '098331' WHERE nama_unit = 'Pengadilan Negeri Kraksaan';
UPDATE unit_kerja SET kode_unit = '099155' WHERE nama_unit = 'Pengadilan Negeri Kuala Kapuas';
UPDATE unit_kerja SET kode_unit = '401918' WHERE nama_unit = 'Pengadilan Negeri Kuala Kurun';
UPDATE unit_kerja SET kode_unit = '098530' WHERE nama_unit = 'Pengadilan Negeri Kuala Simpang';
UPDATE unit_kerja SET kode_unit = '098917' WHERE nama_unit = 'Pengadilan Negeri Kuala Tungkal';
UPDATE unit_kerja SET kode_unit = '097755' WHERE nama_unit = 'Pengadilan Negeri Kudus';
UPDATE unit_kerja SET kode_unit = '097709' WHERE nama_unit = 'Pengadilan Negeri Kuningan';
UPDATE unit_kerja SET kode_unit = '099926' WHERE nama_unit = 'Pengadilan Negeri Kupang';
UPDATE unit_kerja SET kode_unit = '098551' WHERE nama_unit = 'Pengadilan Negeri Kutacane';
UPDATE unit_kerja SET kode_unit = '477380' WHERE nama_unit = 'Pengadilan Negeri Kutai Barat';
UPDATE unit_kerja SET kode_unit = '673020' WHERE nama_unit = 'Pengadilan Negeri Labuan Bajo';
UPDATE unit_kerja SET kode_unit = '099752' WHERE nama_unit = 'Pengadilan Negeri Labuha';
UPDATE unit_kerja SET kode_unit = '098984' WHERE nama_unit = 'Pengadilan Negeri Lahat';
UPDATE unit_kerja SET kode_unit = '098146' WHERE nama_unit = 'Pengadilan Negeri Lamongan';
UPDATE unit_kerja SET kode_unit = '098519' WHERE nama_unit = 'Pengadilan Negeri Langsa';
UPDATE unit_kerja SET kode_unit = '400007' WHERE nama_unit = 'Pengadilan Negeri Larantuka';
UPDATE unit_kerja SET kode_unit = '401926' WHERE nama_unit = 'Pengadilan Negeri Lasusua';
UPDATE unit_kerja SET kode_unit = '477230' WHERE nama_unit = 'Pengadilan Negeri Lembata';
UPDATE unit_kerja SET kode_unit = '098497' WHERE nama_unit = 'Pengadilan Negeri Lhokseumawe';
UPDATE unit_kerja SET kode_unit = '098480' WHERE nama_unit = 'Pengadilan Negeri Lhoksukon';
UPDATE unit_kerja SET kode_unit = '400208' WHERE nama_unit = 'Pengadilan Negeri Limboto';
UPDATE unit_kerja SET kode_unit = '614883' WHERE nama_unit = 'Pengadilan Negeri Liwa';
UPDATE unit_kerja SET kode_unit = '400333' WHERE nama_unit = 'Pengadilan Negeri Lubuk Basung';
UPDATE unit_kerja SET kode_unit = '098970' WHERE nama_unit = 'Pengadilan Negeri Lubuk Linggau';
UPDATE unit_kerja SET kode_unit = '400395' WHERE nama_unit = 'Pengadilan Negeri Lubuk Pakam';
UPDATE unit_kerja SET kode_unit = '098828' WHERE nama_unit = 'Pengadilan Negeri Lubuk Sikaping';
UPDATE unit_kerja SET kode_unit = '098310' WHERE nama_unit = 'Pengadilan Negeri Lumajang';
UPDATE unit_kerja SET kode_unit = '099396' WHERE nama_unit = 'Pengadilan Negeri Luwuk';
UPDATE unit_kerja SET kode_unit = '097890' WHERE nama_unit = 'Pengadilan Negeri Magelang';
UPDATE unit_kerja SET kode_unit = '098387' WHERE nama_unit = 'Pengadilan Negeri Magetan';
UPDATE unit_kerja SET kode_unit = '097691' WHERE nama_unit = 'Pengadilan Negeri Majalengka';
UPDATE unit_kerja SET kode_unit = '099621' WHERE nama_unit = 'Pengadilan Negeri Majene';
UPDATE unit_kerja SET kode_unit = '099617' WHERE nama_unit = 'Pengadilan Negeri Makale';
UPDATE unit_kerja SET kode_unit = '099422' WHERE nama_unit = 'Pengadilan Negeri Makassar';
UPDATE unit_kerja SET kode_unit = '098281' WHERE nama_unit = 'Pengadilan Negeri Malang';
UPDATE unit_kerja SET kode_unit = '673013' WHERE nama_unit = 'Pengadilan Negeri Malili';
UPDATE unit_kerja SET kode_unit = '417704' WHERE nama_unit = 'Pengadilan Negeri Malinau';
UPDATE unit_kerja SET kode_unit = '099638' WHERE nama_unit = 'Pengadilan Negeri Mamuju';
UPDATE unit_kerja SET kode_unit = '099329' WHERE nama_unit = 'Pengadilan Negeri Manado';
UPDATE unit_kerja SET kode_unit = '477399' WHERE nama_unit = 'Pengadilan Negeri Mandailing Natal';
UPDATE unit_kerja SET kode_unit = '400132' WHERE nama_unit = 'Pengadilan Negeri Manna';
UPDATE unit_kerja SET kode_unit = '400069' WHERE nama_unit = 'Pengadilan Negeri Manokwari';
UPDATE unit_kerja SET kode_unit = '400260' WHERE nama_unit = 'Pengadilan Negeri Marabahan';
UPDATE unit_kerja SET kode_unit = '670184' WHERE nama_unit = 'Pengadilan Negeri Marisa';
UPDATE unit_kerja SET kode_unit = '099471' WHERE nama_unit = 'Pengadilan Negeri Maros';
UPDATE unit_kerja SET kode_unit = '099230' WHERE nama_unit = 'Pengadilan Negeri Martapura';
UPDATE unit_kerja SET kode_unit = '672927' WHERE nama_unit = 'Pengadilan Negeri Masamba';
UPDATE unit_kerja SET kode_unit = '099710' WHERE nama_unit = 'Pengadilan Negeri Masohi';
UPDATE unit_kerja SET kode_unit = '099862' WHERE nama_unit = 'Pengadilan Negeri Mataram';
UPDATE unit_kerja SET kode_unit = '099993' WHERE nama_unit = 'Pengadilan Negeri Maumere';
UPDATE unit_kerja SET kode_unit = '098629' WHERE nama_unit = 'Pengadilan Negeri Medan';
UPDATE unit_kerja SET kode_unit = '401925' WHERE nama_unit = 'Pengadilan Negeri Melonguane';
UPDATE unit_kerja SET kode_unit = '099109' WHERE nama_unit = 'Pengadilan Negeri Mempawah';
UPDATE unit_kerja SET kode_unit = '663026' WHERE nama_unit = 'Pengadilan Negeri Menggala';
UPDATE unit_kerja SET kode_unit = '401913' WHERE nama_unit = 'Pengadilan Negeri Mentok';
UPDATE unit_kerja SET kode_unit = '400050' WHERE nama_unit = 'Pengadilan Negeri Merauke';
UPDATE unit_kerja SET kode_unit = '099045' WHERE nama_unit = 'Pengadilan Negeri Metro';
UPDATE unit_kerja SET kode_unit = '098565' WHERE nama_unit = 'Pengadilan Negeri Meulaboh';
UPDATE unit_kerja SET kode_unit = '401903' WHERE nama_unit = 'Pengadilan Negeri Meureudu';
UPDATE unit_kerja SET kode_unit = '098171' WHERE nama_unit = 'Pengadilan Negeri Mojokerto';
UPDATE unit_kerja SET kode_unit = '400430' WHERE nama_unit = 'Pengadilan Negeri Muara Bulian';
UPDATE unit_kerja SET kode_unit = '098900' WHERE nama_unit = 'Pengadilan Negeri Muara Bungo';
UPDATE unit_kerja SET kode_unit = '098991' WHERE nama_unit = 'Pengadilan Negeri Muara Enim';
UPDATE unit_kerja SET kode_unit = '099141' WHERE nama_unit = 'Pengadilan Negeri Muara Teweh';
UPDATE unit_kerja SET kode_unit = '400461' WHERE nama_unit = 'Pengadilan Negeri Muaro';
UPDATE unit_kerja SET kode_unit = '401910' WHERE nama_unit = 'Pengadilan Negeri Mukomuko';
UPDATE unit_kerja SET kode_unit = '400571' WHERE nama_unit = 'Pengadilan Negeri Mungkid';
UPDATE unit_kerja SET kode_unit = '400101' WHERE nama_unit = 'Pengadilan Negeri Nabire';
UPDATE unit_kerja SET kode_unit = '401930' WHERE nama_unit = 'Pengadilan Negeri Namlea';
UPDATE unit_kerja SET kode_unit = '401919' WHERE nama_unit = 'Pengadilan Negeri Nanga Bulik';
UPDATE unit_kerja SET kode_unit = '672948' WHERE nama_unit = 'Pengadilan Negeri Natuna';
UPDATE unit_kerja SET kode_unit = '099802' WHERE nama_unit = 'Pengadilan Negeri Negara';
UPDATE unit_kerja SET kode_unit = '681450' WHERE nama_unit = 'Pengadilan Negeri Ngabang';
UPDATE unit_kerja SET kode_unit = '098242' WHERE nama_unit = 'Pengadilan Negeri Nganjuk';
UPDATE unit_kerja SET kode_unit = '098370' WHERE nama_unit = 'Pengadilan Negeri Ngawi';
UPDATE unit_kerja SET kode_unit = '477270' WHERE nama_unit = 'Pengadilan Negeri Nunukan';
UPDATE unit_kerja SET kode_unit = '681418' WHERE nama_unit = 'Pengadilan Negeri Oelamasi';
UPDATE unit_kerja SET kode_unit = '098366' WHERE nama_unit = 'Pengadilan Negeri Pacitan';
UPDATE unit_kerja SET kode_unit = '098750' WHERE nama_unit = 'Pengadilan Negeri Padang';
UPDATE unit_kerja SET kode_unit = '400188' WHERE nama_unit = 'Pengadilan Negeri Padang Panjang';
UPDATE unit_kerja SET kode_unit = '098722' WHERE nama_unit = 'Pengadilan Negeri Padangsidimpuan';
UPDATE unit_kerja SET kode_unit = '672969' WHERE nama_unit = 'Pengadilan Negeri Pagar Alam';
UPDATE unit_kerja SET kode_unit = '098807' WHERE nama_unit = 'Pengadilan Negeri Painan';
UPDATE unit_kerja SET kode_unit = '099120' WHERE nama_unit = 'Pengadilan Negeri Palangkaraya';
UPDATE unit_kerja SET kode_unit = '098942' WHERE nama_unit = 'Pengadilan Negeri Palembang';
UPDATE unit_kerja SET kode_unit = '099600' WHERE nama_unit = 'Pengadilan Negeri Palopo';
UPDATE unit_kerja SET kode_unit = '099375' WHERE nama_unit = 'Pengadilan Negeri Palu';
UPDATE unit_kerja SET kode_unit = '098391' WHERE nama_unit = 'Pengadilan Negeri Pamekasan';
UPDATE unit_kerja SET kode_unit = '417844' WHERE nama_unit = 'Pengadilan Negeri Pandeglang';
UPDATE unit_kerja SET kode_unit = '099443' WHERE nama_unit = 'Pengadilan Negeri Pangkajene';
UPDATE unit_kerja SET kode_unit = '099010' WHERE nama_unit = 'Pengadilan Negeri Pangkal Pinang';
UPDATE unit_kerja SET kode_unit = '401909' WHERE nama_unit = 'Pengadilan Negeri Pangkalan Balai';
UPDATE unit_kerja SET kode_unit = '099134' WHERE nama_unit = 'Pengadilan Negeri Pangkalan Bun';
UPDATE unit_kerja SET kode_unit = '099492' WHERE nama_unit = 'Pengadilan Negeri Pare';
UPDATE unit_kerja SET kode_unit = '098792' WHERE nama_unit = 'Pengadilan Negeri Pariaman';
UPDATE unit_kerja SET kode_unit = '672980' WHERE nama_unit = 'Pengadilan Negeri Parigi';
UPDATE unit_kerja SET kode_unit = '401921' WHERE nama_unit = 'Pengadilan Negeri Paringin';
UPDATE unit_kerja SET kode_unit = '477352' WHERE nama_unit = 'Pengadilan Negeri Pasaman Barat';
UPDATE unit_kerja SET kode_unit = '681422' WHERE nama_unit = 'Pengadilan Negeri Pasangkayu';
UPDATE unit_kerja SET kode_unit = '681443' WHERE nama_unit = 'Pengadilan Negeri Pasarwajo';
UPDATE unit_kerja SET kode_unit = '662990' WHERE nama_unit = 'Pengadilan Negeri Pasir Pangaraian';
UPDATE unit_kerja SET kode_unit = '098298' WHERE nama_unit = 'Pengadilan Negeri Pasuruan';
UPDATE unit_kerja SET kode_unit = '097762' WHERE nama_unit = 'Pengadilan Negeri Pati';
UPDATE unit_kerja SET kode_unit = '098832' WHERE nama_unit = 'Pengadilan Negeri Payakumbuh';
UPDATE unit_kerja SET kode_unit = '097741' WHERE nama_unit = 'Pengadilan Negeri Pekalongan';
UPDATE unit_kerja SET kode_unit = '098849' WHERE nama_unit = 'Pengadilan Negeri Pekanbaru';
UPDATE unit_kerja SET kode_unit = '400282' WHERE nama_unit = 'Pengadilan Negeri Pelaihari';
UPDATE unit_kerja SET kode_unit = '477255' WHERE nama_unit = 'Pengadilan Negeri Pelalawan';
UPDATE unit_kerja SET kode_unit = '097780' WHERE nama_unit = 'Pengadilan Negeri Pemalang';
UPDATE unit_kerja SET kode_unit = '098701' WHERE nama_unit = 'Pengadilan Negeri Pematang Siantar';
UPDATE unit_kerja SET kode_unit = '401924' WHERE nama_unit = 'Pengadilan Negeri Penajam';
UPDATE unit_kerja SET kode_unit = '099528' WHERE nama_unit = 'Pengadilan Negeri Pinrang';
UPDATE unit_kerja SET kode_unit = '099642' WHERE nama_unit = 'Pengadilan Negeri Polewali';
UPDATE unit_kerja SET kode_unit = '098352' WHERE nama_unit = 'Pengadilan Negeri Ponorogo';
UPDATE unit_kerja SET kode_unit = '099066' WHERE nama_unit = 'Pengadilan Negeri Pontianak';
UPDATE unit_kerja SET kode_unit = '099401' WHERE nama_unit = 'Pengadilan Negeri Poso';
UPDATE unit_kerja SET kode_unit = '672952' WHERE nama_unit = 'Pengadilan Negeri Prabumulih';
UPDATE unit_kerja SET kode_unit = '099912' WHERE nama_unit = 'Pengadilan Negeri Praya';
UPDATE unit_kerja SET kode_unit = '098303' WHERE nama_unit = 'Pengadilan Negeri Probolinggo';
UPDATE unit_kerja SET kode_unit = '401920' WHERE nama_unit = 'Pengadilan Negeri Pulang Pisau';
UPDATE unit_kerja SET kode_unit = '401907' WHERE nama_unit = 'Pengadilan Negeri Pulau Punjung';
UPDATE unit_kerja SET kode_unit = '098036' WHERE nama_unit = 'Pengadilan Negeri Purbalingga';
UPDATE unit_kerja SET kode_unit = '097603' WHERE nama_unit = 'Pengadilan Negeri Purwakarta';
UPDATE unit_kerja SET kode_unit = '097819' WHERE nama_unit = 'Pengadilan Negeri Purwodadi';
UPDATE unit_kerja SET kode_unit = '098001' WHERE nama_unit = 'Pengadilan Negeri Purwokerto';
UPDATE unit_kerja SET kode_unit = '097886' WHERE nama_unit = 'Pengadilan Negeri Purworejo';
UPDATE unit_kerja SET kode_unit = '400194' WHERE nama_unit = 'Pengadilan Negeri Putussibau';
UPDATE unit_kerja SET kode_unit = '099879' WHERE nama_unit = 'Pengadilan Negeri Raba Bima';
UPDATE unit_kerja SET kode_unit = '099670' WHERE nama_unit = 'Pengadilan Negeri Raha';
UPDATE unit_kerja SET kode_unit = '097577' WHERE nama_unit = 'Pengadilan Negeri Rangkasbitung';
UPDATE unit_kerja SET kode_unit = '099265' WHERE nama_unit = 'Pengadilan Negeri Rantau';
UPDATE unit_kerja SET kode_unit = '098675' WHERE nama_unit = 'Pengadilan Negeri Rantau Prapat';
UPDATE unit_kerja SET kode_unit = '097865' WHERE nama_unit = 'Pengadilan Negeri Rembang';
UPDATE unit_kerja SET kode_unit = '098860' WHERE nama_unit = 'Pengadilan Negeri Rengat';
UPDATE unit_kerja SET kode_unit = '477261' WHERE nama_unit = 'Pengadilan Negeri Rokan Hilir';
UPDATE unit_kerja SET kode_unit = '477249' WHERE nama_unit = 'Pengadilan Negeri Rote Ndao';
UPDATE unit_kerja SET kode_unit = '400013' WHERE nama_unit = 'Pengadilan Negeri Ruteng';
UPDATE unit_kerja SET kode_unit = '098455' WHERE nama_unit = 'Pengadilan Negeri Sabang';
UPDATE unit_kerja SET kode_unit = '097823' WHERE nama_unit = 'Pengadilan Negeri Salatiga';
UPDATE unit_kerja SET kode_unit = '099286' WHERE nama_unit = 'Pengadilan Negeri Samarinda';
UPDATE unit_kerja SET kode_unit = '670227' WHERE nama_unit = 'Pengadilan Negeri Sambas';
UPDATE unit_kerja SET kode_unit = '098420' WHERE nama_unit = 'Pengadilan Negeri Sampang';
UPDATE unit_kerja SET kode_unit = '099176' WHERE nama_unit = 'Pengadilan Negeri Sampit';
UPDATE unit_kerja SET kode_unit = '401972' WHERE nama_unit = 'Pengadilan Negeri Sanana';
UPDATE unit_kerja SET kode_unit = '662986' WHERE nama_unit = 'Pengadilan Negeri Sangatta';
UPDATE unit_kerja SET kode_unit = '099113' WHERE nama_unit = 'Pengadilan Negeri Sanggau';
UPDATE unit_kerja SET kode_unit = '477374' WHERE nama_unit = 'Pengadilan Negeri Sarolangun';
UPDATE unit_kerja SET kode_unit = '672931' WHERE nama_unit = 'Pengadilan Negeri Saumlaki';
UPDATE unit_kerja SET kode_unit = '098764' WHERE nama_unit = 'Pengadilan Negeri Sawahlunto';
UPDATE unit_kerja SET kode_unit = '401905' WHERE nama_unit = 'Pengadilan Negeri Sei Rampah';
UPDATE unit_kerja SET kode_unit = '099003' WHERE nama_unit = 'Pengadilan Negeri Sekayu';
UPDATE unit_kerja SET kode_unit = '099595' WHERE nama_unit = 'Pengadilan Negeri Selayar';
UPDATE unit_kerja SET kode_unit = '099890' WHERE nama_unit = 'Pengadilan Negeri Selong';
UPDATE unit_kerja SET kode_unit = '097720' WHERE nama_unit = 'Pengadilan Negeri Semarang';
UPDATE unit_kerja SET kode_unit = '099816' WHERE nama_unit = 'Pengadilan Negeri Semarapura';
UPDATE unit_kerja SET kode_unit = '663012' WHERE nama_unit = 'Pengadilan Negeri Sengeti';
UPDATE unit_kerja SET kode_unit = '099553' WHERE nama_unit = 'Pengadilan Negeri Sengkang';
UPDATE unit_kerja SET kode_unit = '097560' WHERE nama_unit = 'Pengadilan Negeri Serang';
UPDATE unit_kerja SET kode_unit = '400276' WHERE nama_unit = 'Pengadilan Negeri Serui';
UPDATE unit_kerja SET kode_unit = '477343' WHERE nama_unit = 'Pengadilan Negeri Siak Sri Indrapura';
UPDATE unit_kerja SET kode_unit = '098739' WHERE nama_unit = 'Pengadilan Negeri Sibolga';
UPDATE unit_kerja SET kode_unit = '401906' WHERE nama_unit = 'Pengadilan Negeri Sibuhuan';
UPDATE unit_kerja SET kode_unit = '099511' WHERE nama_unit = 'Pengadilan Negeri Sidenreng Rappang';
UPDATE unit_kerja SET kode_unit = '098654' WHERE nama_unit = 'Pengadilan Negeri Sidikalang';
UPDATE unit_kerja SET kode_unit = '098167' WHERE nama_unit = 'Pengadilan Negeri Sidoarjo';
UPDATE unit_kerja SET kode_unit = '098462' WHERE nama_unit = 'Pengadilan Negeri Sigli';
UPDATE unit_kerja SET kode_unit = '400370' WHERE nama_unit = 'Pengadilan Negeri Simalungun';
UPDATE unit_kerja SET kode_unit = '673062' WHERE nama_unit = 'Pengadilan Negeri Simpang Tiga Redelong';
UPDATE unit_kerja SET kode_unit = '098586' WHERE nama_unit = 'Pengadilan Negeri Sinabang';
UPDATE unit_kerja SET kode_unit = '099794' WHERE nama_unit = 'Pengadilan Negeri Singaraja';
UPDATE unit_kerja SET kode_unit = '099070' WHERE nama_unit = 'Pengadilan Negeri Singkawang';
UPDATE unit_kerja SET kode_unit = '098608' WHERE nama_unit = 'Pengadilan Negeri Singkil';
UPDATE unit_kerja SET kode_unit = '099574' WHERE nama_unit = 'Pengadilan Negeri Sinjai';
UPDATE unit_kerja SET kode_unit = '099087' WHERE nama_unit = 'Pengadilan Negeri Sintang';
UPDATE unit_kerja SET kode_unit = '098221' WHERE nama_unit = 'Pengadilan Negeri Situbondo';
UPDATE unit_kerja SET kode_unit = '400565' WHERE nama_unit = 'Pengadilan Negeri Slawi';
UPDATE unit_kerja SET kode_unit = '098082' WHERE nama_unit = 'Pengadilan Negeri Sleman';
UPDATE unit_kerja SET kode_unit = '099769' WHERE nama_unit = 'Pengadilan Negeri Soa';
UPDATE unit_kerja SET kode_unit = '099947' WHERE nama_unit = 'Pengadilan Negeri Soe';
UPDATE unit_kerja SET kode_unit = '098785' WHERE nama_unit = 'Pengadilan Negeri Solok';
UPDATE unit_kerja SET kode_unit = '400075' WHERE nama_unit = 'Pengadilan Negeri Sorong';
UPDATE unit_kerja SET kode_unit = '097940' WHERE nama_unit = 'Pengadilan Negeri Sragen';
UPDATE unit_kerja SET kode_unit = '108025' WHERE nama_unit = 'Pengadilan Negeri Stabat';
UPDATE unit_kerja SET kode_unit = '097631' WHERE nama_unit = 'Pengadilan Negeri Subang';
UPDATE unit_kerja SET kode_unit = '401904' WHERE nama_unit = 'Pengadilan Negeri Suka Makmue';
UPDATE unit_kerja SET kode_unit = '097652' WHERE nama_unit = 'Pengadilan Negeri Sukabumi';
UPDATE unit_kerja SET kode_unit = '663047' WHERE nama_unit = 'Pengadilan Negeri Sukadana';
UPDATE unit_kerja SET kode_unit = '097961' WHERE nama_unit = 'Pengadilan Negeri Sukoharjo';
UPDATE unit_kerja SET kode_unit = '099883' WHERE nama_unit = 'Pengadilan Negeri Sumbawa Besar';
UPDATE unit_kerja SET kode_unit = '400477' WHERE nama_unit = 'Pengadilan Negeri Sumber';
UPDATE unit_kerja SET kode_unit = '097521' WHERE nama_unit = 'Pengadilan Negeri Sumedang';
UPDATE unit_kerja SET kode_unit = '098409' WHERE nama_unit = 'Pengadilan Negeri Sumenep';
UPDATE unit_kerja SET kode_unit = '098921' WHERE nama_unit = 'Pengadilan Negeri Sungai Penuh';
UPDATE unit_kerja SET kode_unit = '099024' WHERE nama_unit = 'Pengadilan Negeri Sungailiat';
UPDATE unit_kerja SET kode_unit = '099439' WHERE nama_unit = 'Pengadilan Negeri Sungguminasa';
UPDATE unit_kerja SET kode_unit = '098111' WHERE nama_unit = 'Pengadilan Negeri Surabaya';
UPDATE unit_kerja SET kode_unit = '097933' WHERE nama_unit = 'Pengadilan Negeri Surakarta';
UPDATE unit_kerja SET kode_unit = '099820' WHERE nama_unit = 'Pengadilan Negeri Tabanan';
UPDATE unit_kerja SET kode_unit = '099340' WHERE nama_unit = 'Pengadilan Negeri Tahuna';
UPDATE unit_kerja SET kode_unit = '673009' WHERE nama_unit = 'Pengadilan Negeri Tais';
UPDATE unit_kerja SET kode_unit = '099464' WHERE nama_unit = 'Pengadilan Negeri Takalar';
UPDATE unit_kerja SET kode_unit = '098502' WHERE nama_unit = 'Pengadilan Negeri Takengon';
UPDATE unit_kerja SET kode_unit = '670191' WHERE nama_unit = 'Pengadilan Negeri Tamiang Layang';
UPDATE unit_kerja SET kode_unit = '400302' WHERE nama_unit = 'Pengadilan Negeri Tanah Grogot';
UPDATE unit_kerja SET kode_unit = '097598' WHERE nama_unit = 'Pengadilan Negeri Tangerang';
UPDATE unit_kerja SET kode_unit = '099244' WHERE nama_unit = 'Pengadilan Negeri Tanjung';
UPDATE unit_kerja SET kode_unit = '098640' WHERE nama_unit = 'Pengadilan Negeri Tanjung Balai';
UPDATE unit_kerja SET kode_unit = '663005' WHERE nama_unit = 'Pengadilan Negeri Tanjung Balai Karimun';
UPDATE unit_kerja SET kode_unit = '477400' WHERE nama_unit = 'Pengadilan Negeri Tanjung Jabung Timur';
UPDATE unit_kerja SET kode_unit = '099031' WHERE nama_unit = 'Pengadilan Negeri Tanjung Karang';
UPDATE unit_kerja SET kode_unit = '400600' WHERE nama_unit = 'Pengadilan Negeri Tanjung Pandan';
UPDATE unit_kerja SET kode_unit = '400421' WHERE nama_unit = 'Pengadilan Negeri Tanjung Pati';
UPDATE unit_kerja SET kode_unit = '098881' WHERE nama_unit = 'Pengadilan Negeri Tanjung Pinang';
UPDATE unit_kerja SET kode_unit = '400291' WHERE nama_unit = 'Pengadilan Negeri Tanjung Redeb';
UPDATE unit_kerja SET kode_unit = '417722' WHERE nama_unit = 'Pengadilan Negeri Tanjung Selor';
UPDATE unit_kerja SET kode_unit = '098590' WHERE nama_unit = 'Pengadilan Negeri Tapaktuan';
UPDATE unit_kerja SET kode_unit = '099272' WHERE nama_unit = 'Pengadilan Negeri Tarakan';
UPDATE unit_kerja SET kode_unit = '098718' WHERE nama_unit = 'Pengadilan Negeri Tarutung';
UPDATE unit_kerja SET kode_unit = '097535' WHERE nama_unit = 'Pengadilan Negeri Tasikmalaya';
UPDATE unit_kerja SET kode_unit = '098682' WHERE nama_unit = 'Pengadilan Negeri Tebing Tinggi';
UPDATE unit_kerja SET kode_unit = '477368' WHERE nama_unit = 'Pengadilan Negeri Tebo';
UPDATE unit_kerja SET kode_unit = '097734' WHERE nama_unit = 'Pengadilan Negeri Tegal';
UPDATE unit_kerja SET kode_unit = '401908' WHERE nama_unit = 'Pengadilan Negeri Teluk Kuantan';
UPDATE unit_kerja SET kode_unit = '097912' WHERE nama_unit = 'Pengadilan Negeri Temanggung';
UPDATE unit_kerja SET kode_unit = '098874' WHERE nama_unit = 'Pengadilan Negeri Tembilahan';
UPDATE unit_kerja SET kode_unit = '099290' WHERE nama_unit = 'Pengadilan Negeri Tenggarong';
UPDATE unit_kerja SET kode_unit = '099731' WHERE nama_unit = 'Pengadilan Negeri Ternate';
UPDATE unit_kerja SET kode_unit = '477218' WHERE nama_unit = 'Pengadilan Negeri Tilamuta';
UPDATE unit_kerja SET kode_unit = '614890' WHERE nama_unit = 'Pengadilan Negeri Timika';
UPDATE unit_kerja SET kode_unit = '099748' WHERE nama_unit = 'Pengadilan Negeri Tobelo';
UPDATE unit_kerja SET kode_unit = '099382' WHERE nama_unit = 'Pengadilan Negeri Toli';
UPDATE unit_kerja SET kode_unit = '099354' WHERE nama_unit = 'Pengadilan Negeri Tondano';
UPDATE unit_kerja SET kode_unit = '098260' WHERE nama_unit = 'Pengadilan Negeri Trenggalek';
UPDATE unit_kerja SET kode_unit = '099727' WHERE nama_unit = 'Pengadilan Negeri Tual';
UPDATE unit_kerja SET kode_unit = '098132' WHERE nama_unit = 'Pengadilan Negeri Tuban';
UPDATE unit_kerja SET kode_unit = '673055' WHERE nama_unit = 'Pengadilan Negeri Tubei';
UPDATE unit_kerja SET kode_unit = '098256' WHERE nama_unit = 'Pengadilan Negeri Tulungagung';
UPDATE unit_kerja SET kode_unit = '477224' WHERE nama_unit = 'Pengadilan Negeri Unaaha';
UPDATE unit_kerja SET kode_unit = '097830' WHERE nama_unit = 'Pengadilan Negeri Ungaran';
UPDATE unit_kerja SET kode_unit = '099972' WHERE nama_unit = 'Pengadilan Negeri Waikabubak';
UPDATE unit_kerja SET kode_unit = '099968' WHERE nama_unit = 'Pengadilan Negeri Waingapu';
UPDATE unit_kerja SET kode_unit = '400044' WHERE nama_unit = 'Pengadilan Negeri Wamena';
UPDATE unit_kerja SET kode_unit = '401927' WHERE nama_unit = 'Pengadilan Negeri Wangi Wangi';
UPDATE unit_kerja SET kode_unit = '099532' WHERE nama_unit = 'Pengadilan Negeri Watampone';
UPDATE unit_kerja SET kode_unit = '099549' WHERE nama_unit = 'Pengadilan Negeri Watansoppeng';
UPDATE unit_kerja SET kode_unit = '098061' WHERE nama_unit = 'Pengadilan Negeri Wates';
UPDATE unit_kerja SET kode_unit = '097954' WHERE nama_unit = 'Pengadilan Negeri Wonogiri';
UPDATE unit_kerja SET kode_unit = '098078' WHERE nama_unit = 'Pengadilan Negeri Wonosari';
UPDATE unit_kerja SET kode_unit = '097929' WHERE nama_unit = 'Pengadilan Negeri Wonosobo';
UPDATE unit_kerja SET kode_unit = '098057' WHERE nama_unit = 'Pengadilan Negeri Yogyakarta';
UPDATE unit_kerja SET kode_unit = '099691' WHERE nama_unit = 'Pengadilan Tinggi Ambon';
UPDATE unit_kerja SET kode_unit = '098434' WHERE nama_unit = 'Pengadilan Tinggi Banda Aceh';
UPDATE unit_kerja SET kode_unit = '097500' WHERE nama_unit = 'Pengadilan Tinggi Bandung';
UPDATE unit_kerja SET kode_unit = '663403' WHERE nama_unit = 'Pengadilan Tinggi Bangka Belitung';
UPDATE unit_kerja SET kode_unit = '099180' WHERE nama_unit = 'Pengadilan Tinggi Banjarmasin';
UPDATE unit_kerja SET kode_unit = '663398' WHERE nama_unit = 'Pengadilan Tinggi Banten';
UPDATE unit_kerja SET kode_unit = '400512' WHERE nama_unit = 'Pengadilan Tinggi Bengkulu';
UPDATE unit_kerja SET kode_unit = '099773' WHERE nama_unit = 'Pengadilan Tinggi Denpasar';
UPDATE unit_kerja SET kode_unit = '664539' WHERE nama_unit = 'Pengadilan Tinggi Gorontalo';
UPDATE unit_kerja SET kode_unit = '097467' WHERE nama_unit = 'Pengadilan Tinggi Jakarta';
UPDATE unit_kerja SET kode_unit = '400503' WHERE nama_unit = 'Pengadilan Tinggi Jambi';
UPDATE unit_kerja SET kode_unit = '097713' WHERE nama_unit = 'Pengadilan Tinggi Jawa Tengah';
UPDATE unit_kerja SET kode_unit = '400022' WHERE nama_unit = 'Pengadilan Tinggi Jayapura';
UPDATE unit_kerja SET kode_unit = '400528' WHERE nama_unit = 'Pengadilan Tinggi Kalimantan Timur';
UPDATE unit_kerja SET kode_unit = '526720' WHERE nama_unit = 'Pengadilan Tinggi Kalimantan Utara';
UPDATE unit_kerja SET kode_unit = '526706' WHERE nama_unit = 'Pengadilan Tinggi Kepulauan Riau';
UPDATE unit_kerja SET kode_unit = '400245' WHERE nama_unit = 'Pengadilan Tinggi Kupang';
UPDATE unit_kerja SET kode_unit = '099418' WHERE nama_unit = 'Pengadilan Tinggi Makassar';
UPDATE unit_kerja SET kode_unit = '664522' WHERE nama_unit = 'Pengadilan Tinggi Maluku Utara';
UPDATE unit_kerja SET kode_unit = '099312' WHERE nama_unit = 'Pengadilan Tinggi Manado';
UPDATE unit_kerja SET kode_unit = '098612' WHERE nama_unit = 'Pengadilan Tinggi Medan';
UPDATE unit_kerja SET kode_unit = '400559' WHERE nama_unit = 'Pengadilan Tinggi Nusa Tenggara Barat';
UPDATE unit_kerja SET kode_unit = '098743' WHERE nama_unit = 'Pengadilan Tinggi Padang';
UPDATE unit_kerja SET kode_unit = '400358' WHERE nama_unit = 'Pengadilan Tinggi Palangkaraya';
UPDATE unit_kerja SET kode_unit = '098938' WHERE nama_unit = 'Pengadilan Tinggi Palembang';
UPDATE unit_kerja SET kode_unit = '526716' WHERE nama_unit = 'Pengadilan Tinggi Papua Barat';
UPDATE unit_kerja SET kode_unit = '400251' WHERE nama_unit = 'Pengadilan Tinggi Pontianak';
UPDATE unit_kerja SET kode_unit = '400492' WHERE nama_unit = 'Pengadilan Tinggi Riau';
UPDATE unit_kerja SET kode_unit = '526710' WHERE nama_unit = 'Pengadilan Tinggi Sulawesi Barat';
UPDATE unit_kerja SET kode_unit = '400534' WHERE nama_unit = 'Pengadilan Tinggi Sulawesi Tengah';
UPDATE unit_kerja SET kode_unit = '400540' WHERE nama_unit = 'Pengadilan Tinggi Sulawesi Tenggara';
UPDATE unit_kerja SET kode_unit = '098104' WHERE nama_unit = 'Pengadilan Tinggi Surabaya';
UPDATE unit_kerja SET kode_unit = '400364' WHERE nama_unit = 'Pengadilan Tinggi Tanjung Karang';
UPDATE unit_kerja SET kode_unit = '400342' WHERE nama_unit = 'Pengadilan Tinggi Yogyakarta';
