'use client'

import { useMemo, useState } from 'react'
import type { PpgAssistedInsight } from '@/lib/ppg/insights'
import { PpgCombobox } from '../PpgCombobox'
import { PpgMultiCombobox } from '../PpgMultiCombobox'

type Control = { id: string; kode: string; nama: string; jenis: string; uraian: string; risk_library_ids: string[] }
type LossEvent = { id: string; kode: string; nama: string; unit: string; level: number; risk_library_id: string }
const input = 'h-9 w-full rounded-lg border border-input bg-white px-3 text-sm font-normal outline-none transition-colors hover:border-ring focus:border-ring focus:ring-2 focus:ring-ring/50 placeholder:text-muted-foreground'

export function ProgramRiskControls({ risks, controls, lossEvents, recommendedCategories, initialRiskId }: { risks: PpgAssistedInsight[]; controls: Control[]; lossEvents: LossEvent[]; recommendedCategories: string[]; initialRiskId?: string }) {
  const initial = risks.some((item) => item.risk_library_id === initialRiskId) ? String(initialRiskId) : ''
  const [riskId, setRiskId] = useState(initial)
  const [controlIds, setControlIds] = useState<string[]>(() => controls.filter((control) => control.risk_library_ids.includes(initial)).map((control) => control.id))
  const categorySet = useMemo(() => new Set(recommendedCategories), [recommendedCategories])
  const risk = risks.find((item) => item.risk_library_id === riskId)
  const eligible = risk ? controls.filter((control) => control.risk_library_ids.includes(risk.risk_library_id)) : []
  const eligibleLosses = risk ? lossEvents.filter((event) => event.risk_library_id === risk.risk_library_id) : []

  return <>
    <div className="xl:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Risiko generik utama</span><PpgCombobox name="risk_library_id" required searchable value={riskId} onValueChange={(value) => { setRiskId(value); setControlIds(controls.filter((control) => control.risk_library_ids.includes(value)).map((control) => control.id)) }} placeholder="Pilih risiko dari hasil analitik" options={risks.map((row) => ({ value: row.risk_library_id, label: `${categorySet.has(row.kategori) ? '★ ' : ''}${row.kode} · ${row.kategori}`, description: `${row.priority.replaceAll('_', ' ')} · skor ${row.priority_score.toFixed(1)} · ${row.affected_pct.toFixed(1)}% Satker terdampak` }))} /></div>
    <div className="xl:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Kontrol terkait</span><PpgMultiCombobox name="control_ids" required disabled={!riskId || !eligible.length} values={controlIds} onValuesChange={setControlIds} placeholder={!riskId ? 'Pilih risiko generik terlebih dahulu' : eligible.length ? 'Konfirmasi satu atau beberapa kontrol yang disarankan' : 'Belum ada kontrol yang dipetakan'} options={eligible.map((row) => ({ value: row.id, label: `${row.kode} · ${row.nama}`, description: `${row.jenis} · ${row.uraian || 'Tanpa uraian'}` }))} />
      {riskId && !eligible.length && <p className="mt-1.5 text-xs text-amber-700">Risiko ini belum memiliki kontrol referensi aktif. Lengkapi relasinya pada Risk and Control Library.</p>}
    </div>
    {risk && <AssistedEvidence key={risk.risk_library_id} risk={risk} />}
    <div className="xl:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Loss event upper-limit pendukung <span className="font-normal text-slate-400">(opsional)</span></span><PpgCombobox name="loss_event_id" searchable disabled={!riskId || !eligibleLosses.length} placeholder={!riskId ? 'Pilih risiko generik terlebih dahulu' : eligibleLosses.length ? 'Pilih bukti kejadian pendukung' : 'Tidak ada upper-limit untuk risiko ini'} options={eligibleLosses.map((event) => ({ value: event.id, label: `${event.kode} · ${event.unit}`, description: `${event.nama} · Level ${event.level}` }))} /></div>
  </>
}

function AssistedEvidence({ risk }: { risk: PpgAssistedInsight }) {
  return <section className="grid gap-4 rounded-xl border border-indigo-200 bg-indigo-50/50 p-4 xl:col-span-4 xl:grid-cols-2">
    <div className="xl:col-span-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="text-sm font-bold text-indigo-950">Dasar analitik otomatis</h4><p className="mt-1 text-xs text-indigo-700">Read-only dan akan dibekukan dalam snapshot ketika draf disimpan.</p></div><span className="rounded-full bg-indigo-700 px-3 py-1 text-[11px] font-bold uppercase text-white">{risk.priority.replaceAll('_', ' ')} · {risk.priority_score.toFixed(1)}</span></div></div>
    <InsightPanel title="Insight A — indeks paparan berbasis data" narrative={risk.insight_a_narrative} score={risk.insight_a_score} stats={[['Baseline outcome A', `${risk.suggested_outcome_a_baseline.toFixed(1)}%`], ['Indikator outcome A', risk.suggested_outcome_a]]} />
    <InsightPanel title="Insight B — realisasi" narrative={risk.insight_b_narrative} score={risk.insight_b_score} stats={[['Satker terdampak', `${risk.affected_pct.toFixed(1)}%`], ['Dampak tinggi', `${risk.high_impact_pct.toFixed(1)}%`], ['Berulang', `${risk.recurring_pct.toFixed(1)}%`]]} />
    <section className={`rounded-xl border p-4 text-xs xl:col-span-2 ${risk.recommended_for_program ? 'border-rose-200 bg-rose-50 text-rose-950' : 'border-emerald-200 bg-emerald-50 text-emerald-950'}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="text-sm font-bold">Landasan Selera Risiko Satker</h4><p className="mt-1 leading-relaxed">{risk.above_appetite_satkers} Satker ({risk.above_appetite_pct.toFixed(1)}%) memiliki residual risk di atas selera; {risk.appetite_set_satkers} Satker sudah menetapkan selera untuk kategori/tahun analisis. Terdapat {risk.upper_limit_satkers} Satker dengan loss event upper-limit.</p></div><span className="rounded-full bg-white px-3 py-1 font-bold">{risk.recommended_for_program ? 'LAYAK DIPERTIMBANGKAN' : 'MONITOR / JUSTIFIKASI OVERRIDE'}</span></div><p className="mt-2 opacity-80">Selera risiko adalah gerbang ex-ante. Upper limit adalah sinyal eskalasi ex-post dan dapat menjadi alasan intervensi UPG Pusat meskipun residual risk masih dalam selera.</p></section>
    <section className="overflow-hidden rounded-xl border border-indigo-100 bg-white xl:col-span-2">
      <div className="flex flex-wrap items-start justify-between gap-2 border-b border-indigo-100 px-4 py-3"><div><h4 className="text-sm font-bold text-slate-900">Pembentuk Skor Insight A</h4><p className="mt-1 max-w-4xl text-[11px] leading-relaxed text-slate-500">Skor A adalah jumlah kontribusi lima komponen: skor normalisasi 0–100 × bobot. Bobot merupakan parameter kebijakan awal yang perlu dikalibrasi dan disahkan berdasarkan data historis serta pertimbangan ahli.</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-600">{risk.insight_a_method_version}</span></div>
      <div className="overflow-x-auto"><table className="min-w-full text-left text-[11px]"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-2 font-semibold">Komponen</th><th className="px-4 py-2 font-semibold">Nilai data</th><th className="px-4 py-2 text-right font-semibold">Skor</th><th className="px-4 py-2 text-right font-semibold">Bobot</th><th className="px-4 py-2 text-right font-semibold">Kontribusi</th></tr></thead><tbody className="divide-y divide-slate-100">{risk.insight_a_components.map((component) => <tr key={component.key} title={component.explanation}><td className="px-4 py-2 font-semibold text-slate-700">{component.label}</td><td className="px-4 py-2 text-slate-600">{component.raw_display}</td><td className="px-4 py-2 text-right text-slate-700">{component.normalized_score.toFixed(1)}</td><td className="px-4 py-2 text-right text-slate-700">{(component.weight * 100).toFixed(0)}%</td><td className="px-4 py-2 text-right font-semibold text-indigo-700">{component.contribution.toFixed(1)}</td></tr>)}</tbody><tfoot className="border-t border-indigo-100 bg-indigo-50"><tr><td colSpan={4} className="px-4 py-2 text-right font-bold text-indigo-950">Total Skor Insight A</td><td className="px-4 py-2 text-right font-bold text-indigo-700">{risk.insight_a_score.toFixed(1)}</td></tr></tfoot></table></div>
    </section>
    <div className="grid gap-2 rounded-xl bg-white p-3 text-xs sm:grid-cols-3 xl:col-span-2"><Metric label="Klaster 1 · kritis" value={`${risk.cluster_1_satkers} Satker`} /><Metric label="Klaster 2 · terbatas" value={`${risk.cluster_2_satkers} Satker`} /><Metric label="Klaster 3 · monitoring" value={`${risk.cluster_3_satkers} Satker`} /></div>
    <section className="grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 xl:col-span-2 xl:grid-cols-4"><div className="xl:col-span-4"><h4 className="text-sm font-bold text-amber-950">KRI yang disarankan mesin</h4><p className="mt-1 text-xs text-amber-800">Indikator berasal dari pola kegagalan kontrol/kejadian. UPG Pusat dapat menyesuaikan ambangnya.</p><p className="mt-2 rounded-lg bg-white p-3 text-sm font-medium text-slate-700">{risk.suggested_kri}</p></div><input type="hidden" name="kri_indikator" value={risk.suggested_kri} /><label className="grid gap-1 text-xs font-semibold text-slate-600">Hijau<input name="kri_ambang_hijau" required defaultValue={risk.suggested_kri_green} className={input} /></label><label className="grid gap-1 text-xs font-semibold text-slate-600">Waspada<input name="kri_ambang_waspada" required defaultValue={risk.suggested_kri_warning} className={input} /></label><label className="grid gap-1 text-xs font-semibold text-slate-600">Merah<input name="kri_ambang_merah" required defaultValue={risk.suggested_kri_red} className={input} /></label></section>
    <section className="grid gap-3 rounded-xl border border-cyan-200 bg-cyan-50 p-4 xl:col-span-2 xl:grid-cols-4"><div className="xl:col-span-4"><h4 className="text-sm font-bold text-cyan-950">Outcome yang diturunkan dari insight</h4><p className="mt-1 text-xs text-cyan-800">Indikator dan baseline dikunci dari analitik. UPG Pusat menetapkan target akhirnya.</p></div><Outcome title="Outcome A · perubahan paparan" indicator={risk.suggested_outcome_a} baseline={risk.suggested_outcome_a_baseline} target={risk.suggested_outcome_a_target} prefix="outcome_a" /><Outcome title="Outcome B · realisasi risiko" indicator={risk.suggested_outcome_b} baseline={risk.suggested_outcome_b_baseline} target={risk.suggested_outcome_b_target} prefix="outcome_b" />
      <input type="hidden" name="indikator_program" value={risk.suggested_outcome_b} /><input type="hidden" name="baseline_indikator" value={risk.suggested_outcome_b_baseline} /><input type="hidden" name="satuan_indikator" value="% Satker" /><input type="hidden" name="arah_target" value="maksimal" /><input type="hidden" name="sumber_data_indikator" value="Advanced analytics PPG · laporan gratifikasi dan LED tervalidasi" />
    </section>
  </section>
}

function InsightPanel({ title, narrative, score, stats }: { title: string; narrative: string; score: number; stats: [string, string][] }) { return <article className="rounded-xl bg-white p-4"><div className="flex justify-between gap-3 text-xs"><b>{title}</b><span>{score.toFixed(1)}/100</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-gradient-to-r from-indigo-600 to-cyan-500" style={{ width: `${Math.max(2, score)}%` }} /></div><p className="mt-3 text-xs leading-relaxed text-slate-600">{narrative}</p><dl className="mt-3 grid gap-2 sm:grid-cols-2">{stats.map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-2 text-[11px]"><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-semibold text-slate-800">{value}</dd></div>)}</dl></article> }
function Outcome({ title, indicator, baseline, target, prefix }: { title: string; indicator: string; baseline: number; target: number; prefix: 'outcome_a' | 'outcome_b' }) { return <div className="rounded-xl bg-white p-3 xl:col-span-2"><b className="text-xs text-cyan-950">{title}</b><p className="mt-2 text-xs text-slate-600">{indicator}</p><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-slate-50 p-2 text-xs"><span className="block text-slate-500">Baseline mesin</span><b>{baseline.toFixed(1)}%</b></div><label className="grid gap-1 text-xs font-semibold text-slate-600">Target UPG Pusat (%)<input name={`${prefix}_target_pct`} type="number" min="0" max="100" step="0.01" required defaultValue={target} className={input} /></label></div><input type="hidden" name={`${prefix}_indikator`} value={indicator} /><input type="hidden" name={`${prefix}_baseline_pct`} value={baseline} />{prefix === 'outcome_b' && <input type="hidden" name="target_indikator" value={target} />}</div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 px-3 py-2"><span className="block text-[11px] text-slate-500">{label}</span><b>{value}</b></div> }
