'use client'

import { useMemo, useState } from 'react'
import { Check, ChevronDown, Search } from 'lucide-react'

type ControlOption = { id: string; kode: string; nama: string; jenis: string; uraian: string }
type LibraryOption = { id: string; kode: string; kategori: string; proses_bisnis: string; subproses_bisnis: string; peristiwa: string; controls?: ControlOption[] }

export function RiskLibrarySelect({ options }: { options: LibraryOption[] }) {
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<LibraryOption | null>(null)
  const [selectedControls, setSelectedControls] = useState<string[]>([])
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return term ? options.filter((item) => [item.kode, item.kategori, item.proses_bisnis, item.subproses_bisnis, item.peristiwa].some((value) => value.toLowerCase().includes(term))) : options }, [options, search])

  return <div className="relative sm:col-span-2">
    <input type="hidden" name="risk_library_id" value={selected?.id ?? ''} required />
    <label className="space-y-1 text-xs font-semibold text-slate-600"><span>Risiko generik dari Risk and Control Library</span>
      <button type="button" onClick={() => setOpen((value) => !value)} className="flex h-9 w-full items-center justify-between gap-3 rounded-lg border border-input bg-transparent px-3 text-left text-sm transition-colors outline-none hover:border-ring focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/50">
        <span className={selected ? 'min-w-0' : 'text-slate-400'}>{selected ? <><b className="font-mono text-indigo-700">{selected.kode}</b><span className="ml-2 text-slate-600">{selected.peristiwa}</span></> : 'Pilih risiko referensi'}</span><ChevronDown className={`h-4 w-4 shrink-0 transition ${open ? 'rotate-180' : ''}`} />
      </button>
    </label>
    {open ? <div className="absolute z-30 mt-2 w-full overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl"><div className="flex items-center gap-2 border-b p-2"><Search className="h-4 w-4 text-slate-400" /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari kode, kategori, proses, atau peristiwa..." className="w-full bg-transparent text-sm outline-none" /></div><div className="max-h-72 overflow-y-auto">{filtered.length ? filtered.map((item) => <button key={item.id} type="button" onClick={() => { setSelected(item); setSelectedControls([]); setOpen(false); setSearch('') }} className="flex w-full items-start gap-2 border-b border-slate-100 px-3 py-3 text-left text-sm last:border-0 hover:bg-indigo-50">{selected?.id === item.id ? <Check className="mt-0.5 h-4 w-4 shrink-0 text-indigo-700" /> : <span className="h-4 w-4 shrink-0" />}<span className="min-w-0"><b className="font-mono text-indigo-700">{item.kode}</b><span className="mt-1 block line-clamp-2 text-slate-700">{item.peristiwa}</span><span className="mt-1 block text-xs text-slate-400">{item.kategori} · {item.proses_bisnis}{item.subproses_bisnis ? ` / ${item.subproses_bisnis}` : ''}</span></span></button>) : <p className="p-5 text-center text-sm text-slate-500">Tidak ada hasil.</p>}</div></div> : null}
    {selected ? <div className="mt-2 rounded-xl bg-indigo-50 p-3 text-xs text-indigo-900"><b>Referensi generik UPG Pusat</b><span className="mt-1 block">{selected.kategori} · {selected.proses_bisnis}{selected.subproses_bisnis ? ` / ${selected.subproses_bisnis}` : ''}</span></div> : null}
    {selected ? <div className="mt-3 overflow-hidden rounded-xl border border-slate-200"><div className="bg-slate-50 px-3 py-2"><p className="text-xs font-semibold text-slate-700">Kontrol yang benar-benar diterapkan satker</p><p className="mt-0.5 text-xs text-slate-500">Pilih kontrol, nilai efektivitasnya, dan cantumkan tautan bukti. Bukti wajib untuk penilaian “Sebagian” atau “Efektif”.</p></div>{selected.controls?.length ? <div className="divide-y divide-slate-100">{selected.controls.map((control) => { const checked = selectedControls.includes(control.id); return <div key={control.id} className="grid gap-2 p-3 md:grid-cols-[minmax(14rem,1.2fr)_minmax(10rem,0.7fr)_minmax(16rem,1fr)] md:items-center"><label className="flex items-start gap-2 text-sm font-normal text-slate-700"><input type="checkbox" name="control_ids" value={control.id} checked={checked} onChange={(event) => setSelectedControls((current) => event.target.checked ? [...current, control.id] : current.filter((id) => id !== control.id))} className="mt-1" /><span><b className="font-mono text-indigo-700">{control.kode}</b> · {control.nama}<span className="mt-0.5 block text-xs text-slate-500">{control.jenis} · {control.uraian || 'Tanpa uraian'}</span></span></label><select name={`efektivitas:${control.id}`} disabled={!checked} defaultValue="belum_dinilai" className="h-9 rounded-lg border border-input bg-white px-3 text-sm font-normal disabled:bg-slate-100"><option value="belum_dinilai">Belum dinilai</option><option value="tidak_efektif">Tidak efektif</option><option value="sebagian">Sebagian efektif</option><option value="efektif">Efektif</option></select><input name={`bukti:${control.id}`} disabled={!checked} type="url" placeholder="https://drive.google.com/... atau OneDrive" className="h-9 rounded-lg border border-input bg-white px-3 text-sm font-normal outline-none disabled:bg-slate-100" /></div> })}</div> : <p className="p-4 text-sm text-amber-700">Belum ada kontrol aktif yang dipetakan ke risiko ini.</p>}</div> : null}
  </div>
}
