import type { InterviewQuestion, InterviewSnapshot, QuestionResponse } from './types'

const commonProbes = [
  'Bisa diberikan satu contoh konkretnya?',
  'Kapan terakhir Anda mengalami atau melihat hal tersebut?',
  'Coba ceritakan prosesnya dari awal sampai selesai.',
  'Siapa yang mengambil keputusan pada saat itu?',
  'Apa yang berubah setelah tindakan tersebut dilakukan?',
  'Bagaimana Anda mengetahui bahwa cara tersebut efektif?',
  'Apakah praktik tersebut dilakukan dengan cara yang sama pada kasus lain?',
  'Adakah dokumen, data, aplikasi, atau contoh kasus yang dapat menunjukkan hal tersebut?',
  'Jika pimpinan atau petugasnya berganti besok, apakah sistem ini tetap berjalan? Mengapa?',
  'Apabila pertanyaan yang sama kami tanyakan kepada pegawai lain, apakah mereka akan memberikan penjelasan yang sama?',
] as const

const rows: Array<[string,string,number,string,string,boolean,string,string,string,string[]]> = [
  ['D1.1','Perubahan Sejak Evaluasi Terakhir',4,'Tindak lanjut, dampak, pembelajaran, keberlanjutan','Wajib',false,'Pimpinan/Tim ZI','Sejak evaluasi terakhir, apa perbaikan paling konkret, dampak terukurnya, pembelajaran dari hal yang belum berhasil, dan bagaimana keberlanjutannya dijamin?','Minta catatan evaluasi lama, rencana aksi, PIC, data sebelum-sesudah, koreksi metode, SOP, dan monitoring. Pilih NA bila belum pernah dievaluasi.',['Apa kondisi sebelum dan sesudah perbaikan?','Apa dampak yang dapat diukur?','Upaya apa yang belum berhasil dan mengapa?','Bagaimana memastikan perbaikan tersebut tetap berjalan?']],
  ['D1.2','Perubahan Sejak Evaluasi Terakhir',2,'Validasi pengalaman aparatur','Uji Acak',false,'Pegawai nonpimpinan','Perubahan apa yang paling Anda rasakan sejak evaluasi terakhir, dan apakah sesuai dengan klaim pimpinan?','Pilih pegawai acak lintas fungsi. Pilih NA bila belum pernah dievaluasi.',['Apa yang berbeda dibanding sebelumnya?','Apakah perubahan itu juga dirasakan pegawai lain?','Apakah perubahan sesuai dengan yang disampaikan pimpinan?']],
  ['D2.1','Pendalaman Catatan ANDOK / Panel TPI',5,'Klarifikasi catatan material dan koreksi','Klarifikasi ANDOK',true,'Pimpinan/PIC terkait','Untuk setiap catatan material ANDOK/Panel—terutama status Tidak Diusulkan—jelaskan kondisi aktual, akar masalah, konsistensi data-dokumen-praktik, koreksi, risiko, dan bukti implementasinya.','Gunakan isu spesifik pada lembar persiapan; uji sampel data, tanggal, log, PIC, tenggat, mitigasi, dan bukti koreksi. Pilih NA bila tidak ada catatan material.',['Apa kondisi aktual saat ini?','Apa akar masalahnya?','Apakah data, dokumen, dan praktik lapangan konsisten?','Risiko apa yang masih tersisa?','Bukti apa yang menunjukkan koreksi benar-benar diterapkan?']],
  ['D3.1','Komitmen Pimpinan',4,'Motivasi, keteladanan, dan keberanian moral','Wajib',true,'Ketua/Wakil Ketua','Apa tujuan spesifik pembangunan ZI di satker ini, dan contoh keputusan sulit apa yang menunjukkan pimpinan konsisten menjadi teladan integritas?','Hubungkan dengan masalah satker, kebutuhan pengguna, risiko integritas, target outcome, tekanan yang dihadapi, dasar keputusan, dan tindak lanjut.',['Apa perubahan yang ingin dicapai?','Bagaimana tujuan itu diterjemahkan dalam pekerjaan sehari-hari?','Apa situasi dan keputusan sulit yang diambil?','Apa konsekuensi keputusan itu dan dampaknya bagi pegawai?']],
  ['D3.2','Komitmen Pimpinan',4,'Pernyataan komitmen dan kontrol pengganti','Wajib',true,'Ketua, Wakil, Panitera, Sekretaris','Apakah setiap unsur pimpinan bersedia membuat pernyataan siap mengundurkan diri jika terjadi OTT atau pelanggaran berat integritas? Jika tidak, apa alasannya dan kontrol pengganti yang dijalankan?','Catat jawaban setiap unsur; bila tidak bersedia, gali pemaknaan tanggung jawab, kontrol preventif/detektif, monitoring, dan sanksi.',['Sejauh mana pimpinan mempertanggungjawabkan kegagalan pengendalian?','Apakah bentuk pertanggungjawaban pernah dibahas?','Kontrol apa yang memastikan akuntabilitas pimpinan?']],
  ['D3.3','Komitmen Pimpinan',4,'Penanganan pelanggaran dan konflik kepentingan','Wajib',true,'Pimpinan','Bagaimana indikasi pelanggaran, konflik kepentingan, dan laporan pegawai diterima, dilindungi, diperiksa, dieskalasi, dan ditindaklanjuti?','Minta kanal, SLA, perlindungan pelapor, deklarasi/recusal, register, pembatasan akses, dokumentasi, contoh kasus, dan tindak lanjut.',['Bagaimana identitas pelapor dilindungi?','Siapa yang memiliki akses dan melakukan pemeriksaan?','Kapan laporan dieskalasi?','Bagaimana keputusan pengalihan tugas didokumentasikan?']],
  ['D3.4','Komitmen Pimpinan',2,'Kendala sumber daya dan integrasi sistem','Pendalaman',true,'Ketua/Wakil/Sekretaris','Bagaimana kendala SDM atau anggaran diatasi tanpa menurunkan kualitas dan integritas, serta bagaimana perubahan diintegrasikan ke sistem kerja?','Minta prioritas, realokasi, penguatan kompetensi, mitigasi risiko, SOP, target kinerja, onboarding, dan pengawasan rutin.',['Kendala mana yang paling memengaruhi kualitas pengendalian?','Prioritas apa yang dipilih dan apa dasar keputusannya?','Bagian mana yang masih bergantung pada figur tertentu?']],
  ['D3.5','Komitmen Pimpinan',2,'Validasi keteladanan pimpinan','Uji Acak',true,'Pegawai nonpimpinan','Apa contoh keteladanan dan respons pimpinan terhadap pelanggaran yang benar-benar pernah Anda lihat?','Bandingkan dengan jawaban pimpinan dan bukti tindakan.',['Apa yang dilakukan pimpinan?','Apakah perlakuannya berbeda berdasarkan jabatan atau kedekatan?','Bagaimana tindak lanjutnya?']],
  ['D4.1','Manajemen Perubahan',4,'Internalisasi nilai dan perubahan perilaku','Wajib',true,'Tim ZI/SDM/Pegawai','Bagaimana nilai ZI diinternalisasikan hingga menjadi kebiasaan, dan perilaku apa yang benar-benar berubah pada pimpinan maupun pegawai?','Minta metode, frekuensi, contoh kasus, coaching, uji pemahaman pegawai acak, serta perubahan disiplin, layanan, dan transparansi.',['Perilaku apa yang berubah pada pimpinan?','Perilaku apa yang berubah pada pegawai?','Berikan contoh perubahan yang dapat diamati.']],
  ['D4.2','Manajemen Perubahan',3,'Resistensi, keterlibatan, dan koreksi program','Wajib',true,'Pimpinan/Tim ZI','Resistensi apa yang muncul, bagaimana seluruh unit dilibatkan, dan program apa yang diubah atau dihentikan karena tidak efektif?','Minta pihak terdampak, akar resistensi, intervensi, komunikasi dua arah, evaluasi, hasil, dan pembelajaran.',['Dari mana resistensi muncul?','Bagaimana pimpinan atau Tim ZI meresponsnya?','Bagaimana ketidakefektifan program diketahui?','Apa yang dilakukan sebagai penggantinya?']],
  ['D4.3','Manajemen Perubahan',3,'Pengukuran dan institusionalisasi perubahan','Wajib',true,'Pimpinan/Tim ZI/SDM','Bagaimana perubahan perilaku diukur, dipantau, dan dilembagakan agar tidak bergantung pada figur atau kegiatan seremonial?','Minta indikator perilaku, survei/observasi, tren disiplin/pengaduan, SOP, target kinerja, kaderisasi, dan forum evaluasi.',['Indikator apa yang digunakan dan seberapa sering dipantau?','Siapa yang melakukan evaluasi?','Bagaimana hasil evaluasi digunakan untuk koreksi?','Apakah perubahan sudah masuk SOP, kebijakan, atau sistem?']],
  ['D5.1','Kontribusi Agen Perubahan',4,'Inisiatif dan lima peran agen perubahan','Wajib',true,'Agen Perubahan','Jelaskan satu perubahan yang diinisiasi agen dan bagaimana agen berperan sebagai katalis, penggerak, pemberi solusi, mediator, serta penghubung.','Minta masalah awal, kontribusi personal, pihak terlibat, resistensi, tahapan implementasi, solusi, komunikasi, dan hasil.',['Apa yang dilakukan sendiri oleh agen tersebut?','Bagaimana agen menjadi katalis dan penggerak?','Solusi apa yang diberikan?','Bagaimana agen memediasi dan menghubungkan antarunit?']],
  ['D5.2','Kontribusi Agen Perubahan',3,'Dampak dan dukungan organisasi','Wajib',true,'Pimpinan/Agen/Pegawai','Apa dampak terukur dari gerakan agen perubahan dan dukungan apa yang diberikan pimpinan serta lingkungan kerja?','Triangulasi dengan data penggunaan/hasil, bukti sebelum-sesudah, keputusan pimpinan, sumber daya, dan umpan balik pegawai.',['Apa indikator keberhasilannya?','Adakah hasil yang dapat diukur?','Dukungan apa yang diberikan pimpinan?','Apakah lingkungan kerja mendukung peran agen?']],
  ['D5.3','Kontribusi Agen Perubahan',2,'Kredibilitas agen di mata pegawai','Uji Acak',true,'Pegawai nonpimpinan','Siapa agen perubahan di unit Anda dan perubahan nyata apa yang ia dorong?','Ketidaktahuan luas atau tidak adanya contoh konkret mengindikasikan peran formalitas.',['Bagaimana Anda mengetahui perannya?','Apa dampaknya terhadap pekerjaan atau perilaku pegawai?','Apakah pegawai lain akan menyebut orang dan perubahan yang sama?']],
  ['D6.1','Integritas & Budaya Antikorupsi',4,'Pedoman gratifikasi, UPG, dan pemahaman pegawai','Wajib',true,'Pimpinan/UPG/Pegawai','Apakah pengendalian gratifikasi telah mengikuti SK Kabawas No. 29/2025 sebagaimana diubah No. 75/2026, bagaimana UPG bekerja, dan apa yang dilakukan pegawai saat menerima pemberian?','Minta kebijakan internal, sosialisasi, register/laporan UPG, batas waktu dan kanal pelaporan, penolakan, penanganan kasus, serta tindak lanjut.',['Kepada siapa pegawai melapor?','Bagaimana UPG memproses laporan?','Bagaimana perubahan ketentuan diterapkan?','Dapatkah diberikan contoh kasus yang pernah ditangani?']],
  ['D6.2','Integritas & Budaya Antikorupsi',3,'WBS, konflik kepentingan, dan budaya speak-up','Wajib',true,'Pimpinan/Pengelola WBS/Pegawai','Bagaimana WBS dan penanganan benturan kepentingan menjamin kerahasiaan, perlindungan pelapor, deklarasi, pemeriksaan, pengalihan tugas, dan tindak lanjut?','Minta SLA, akses terbatas, register, statistik kasus, contoh recusal, status tindak lanjut, dan uji rasa aman pegawai untuk melapor.',['Bagaimana identitas pelapor dilindungi?','Siapa yang menilai benturan kepentingan?','Apakah pekerjaan dapat dialihkan?','Bagaimana pelapor mengetahui laporannya ditindaklanjuti?']],
  ['D6.3','Integritas & Budaya Antikorupsi',3,'Pengendalian BMN, anggaran, dan pengadaan','Wajib',true,'Sekretaris/Keuangan/PPK','Apa kontrol utama untuk mencegah penyalahgunaan BMN, realisasi anggaran tidak sah, dan konflik/pengaturan dalam pengadaan?','Uji otorisasi, pemisahan fungsi, register/log, stock opname, verifikasi bukti, survei harga, evaluasi penyedia, pemeriksaan hasil, dan audit trail.',['Bagaimana penyalahgunaan BMN dicegah?','Bagaimana dasar pembayaran diverifikasi?','Bagaimana konflik kepentingan pengadaan dicegah?','Pernahkah kontrol mendeteksi masalah?']],
  ['D6.4','Integritas & Budaya Antikorupsi',3,'Transparansi biaya dan proses layanan perkara','Wajib',true,'Panitera/PIC layanan','Bagaimana biaya eksekusi, pemeriksaan setempat, sumpah, dan proses mediasi dikendalikan agar transparan serta bebas pungutan atau konflik kepentingan?','Minta dasar tarif, rekening resmi, publikasi, bukti pembayaran/realisasi, pengembalian sisa, rekonsiliasi, penunjukan, komunikasi, dan kanal pengaduan.',['Bagaimana biaya ditetapkan dan diumumkan?','Bagaimana pembayaran dicatat?','Bagaimana pungutan di luar ketentuan dicegah?','Bagaimana benturan kepentingan dikendalikan?']],
  ['D6.5','Integritas & Budaya Antikorupsi',3,'Pengawasan eksternal dan perbaikan sistem','Wajib',true,'Pimpinan','Bagaimana satker membuka diri terhadap pengawasan eksternal dan mengubah temuan audit atau pelanggaran menjadi perbaikan sistem yang mencegah pengulangan?','Minta akses data, rekomendasi terakhir, akar masalah, rencana aksi, PIC, tenggat, verifikasi, sanksi, dan perubahan kontrol.',['Bagaimana temuan dianalisis dan akar masalah ditentukan?','Apa yang dilakukan agar masalah tidak berulang?','Adakah temuan yang menghasilkan perubahan sistem?']],
  ['D6.6','Integritas & Budaya Antikorupsi',2,'Pemahaman risiko korupsi per fungsi','Uji Acak',true,'Pegawai lintas fungsi','Apa risiko korupsi paling nyata dalam pekerjaan Anda dan kontrol apa yang benar-benar dijalankan setiap hari?','Jawaban harus spesifik sesuai fungsi dan konsisten dengan prosedur serta bukti praktik.',['Mengapa bagian proses itu berisiko?','Bagaimana kontrol dijalankan sehari-hari?','Pernahkah kontrol tersebut mendeteksi masalah?']],
  ['D7.1','Akuntabilitas Kinerja',4,'Konsistensi dokumen dan kualitas indikator','Wajib',false,'Pimpinan/Pengelola Kinerja','Ambil satu sasaran: bagaimana Renstra, RKT, Perjanjian Kinerja, indikator, anggaran, LKjIP, dan praktik pengendalian kinerja saling konsisten dan berorientasi hasil?','Uji target, baseline, formula, sumber data, penanggung jawab, realisasi, output-outcome, monitoring, analisis penyebab, dan peran pimpinan.',['Apakah indikator menggambarkan hasil yang ingin dicapai?','Apakah anggaran mendukung sasaran tersebut?','Bagaimana deviasi kinerja ditindaklanjuti?']],
  ['D7.2','Akuntabilitas Kinerja',3,'Pemanfaatan e-Court dan data untuk perbaikan','Wajib',false,'Pimpinan/Panitera/PIC Kinerja','Bagaimana data kinerja dan pemanfaatan e-Court digunakan untuk mengambil keputusan, mengatasi deviasi target, dan meningkatkan kecepatan serta akses penyelesaian perkara?','Minta tren penggunaan, hambatan, forum review, keputusan berbasis data, rencana aksi, eskalasi, dan hasil setelah perbaikan.',['Data apa yang digunakan dan masalah apa yang ditemukan?','Keputusan apa yang diambil?','Apa hasil setelah keputusan diterapkan?','Apa dampaknya terhadap waktu, akses, atau efisiensi?']],
  ['D8.1','Pelayanan Publik',4,'Kebutuhan, standar, akses, dan kepuasan pengguna','Wajib',false,'Pimpinan/Pelayanan/PIC Survei','Bagaimana kebutuhan pengguna dan kelompok rentan dipetakan, standar layanan dipenuhi, serta hasil survei dan pengaduan digunakan untuk memperbaiki akses, biaya, waktu, dan kepastian layanan?','Minta data pengguna, journey layanan, persyaratan/tarif/SLA, jumlah dan keterwakilan responden, tren kepuasan, keluhan dominan, serta tindak lanjut.',['Bagaimana kebutuhan pengguna dipetakan?','Bagaimana aksesibilitas kelompok rentan diuji?','Masalah apa yang paling sering muncul?','Perbaikan apa yang dilakukan dan apa dampaknya?']],
  ['D8.2','Pelayanan Publik',3,'Google Review dan kanal pengaduan publik','Wajib',false,'Pengelola Pengaduan/Pimpinan','Apa temuan utama Google Review dan kanal pengaduan lain, serta bagaimana ulasan negatif diterima, direspons, diselesaikan, dan diubah menjadi perbaikan layanan?','Periksa rating, isi ulasan, waktu respons, SLA, klasifikasi, status, akar masalah, bukti penyelesaian, dan perubahan layanan.',['Siapa yang memantau kanal tersebut?','Bagaimana masalah diverifikasi dan diselesaikan?','Adakah perubahan layanan yang lahir dari ulasan pengguna?']],
  ['D8.3','Pelayanan Publik',5,'Relevansi, pemanfaatan, dampak, dan uji inovasi','Wajib',false,'PIC Inovasi/Petugas','Masalah pengguna apa yang diselesaikan inovasi utama, berapa pemanfaatan dan dampaknya dibanding sebelumnya, dan dapatkah ditunjukkan satu proses nyata dari awal sampai selesai?','Minta demo/sampel, log dan statistik pengguna, perubahan alur, waktu/biaya, kepuasan, kegagalan, before-after, SOP, serta tindak lanjut.',['Bagaimana kondisi sebelum inovasi?','Mengapa inovasi tersebut dipilih?','Berapa tingkat pemanfaatannya?','Apa perubahan waktu, biaya, dan kepuasan?','Tunjukkan satu proses nyata dari awal sampai selesai.']],
  ['D9.1','Komitmen ZI Berkelanjutan',3,'Strategi pasca-evaluasi dan ketahanan sistem','Wajib',false,'Pimpinan/Tim ZI','Apa strategi pasca-evaluasi untuk menjaga ZI saat terjadi rotasi, menghadapi risiko 12–24 bulan, dan memastikan evaluasi serta koreksi berjalan berkala?','Minta rencana tahunan, target, PIC, sumber daya, kaderisasi/serah terima, early warning, mitigasi, kalender review, dashboard, dan forum tindak lanjut.',['Apa risiko keberlanjutan terbesar dalam 12–24 bulan?','Apa yang sudah dilembagakan?','Siapa yang memastikan koreksi dilaksanakan?','Bagaimana progres dilaporkan kepada pimpinan?']],
  ['D9.2','Komitmen ZI Berkelanjutan',2,'Praktik terbaik dan pembelajaran','Penutup',false,'Pimpinan/Tim ZI','Praktik terbaik apa yang layak direplikasi dan apa pelajaran terpenting dari keberhasilan maupun kegagalan pembangunan ZI?','Minta contoh konkret, bukti hasil, prasyarat replikasi, sumber daya, koreksi pendekatan, dan pembelajaran organisasi.',['Mengapa praktik itu berhasil?','Apa prasyarat agar dapat direplikasi?','Upaya apa yang belum sesuai harapan?','Apa yang dipelajari dan kemudian diubah?']],
  ['D9.3','Komitmen ZI Berkelanjutan',2,'Saran dan pernyataan penutup','Penutup',false,'Pimpinan','Apa saran untuk Reformasi Birokrasi/ZI di Mahkamah Agung, dan apa komitmen atau catatan akhir satker?','Catat saran kebijakan/sistem/dukungan pusat, komitmen akhir, serta isu material yang belum tersampaikan.',['Apa satu atau dua perubahan terpenting untuk memperkuat RB dan ZI?','Apa satu keberhasilan, satu risiko, dan satu komitmen perbaikan?','Adakah hal penting yang belum kami tanyakan?']],
]

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = rows.map((row, index) => ({
  no: index + 1,
  code: row[0],
  dimension: row[1],
  minutes: row[2],
  indicator: row[3],
  kind: row[4] as InterviewQuestion['kind'],
  critical: row[5],
  target: row[6],
  question: row[7],
  evidence: row[8],
  probes: row[9],
  role: row[1].startsWith('Komitmen Pimpinan') || row[1].startsWith('Manajemen Perubahan') || row[1].startsWith('Kontribusi') || row[1].startsWith('Integritas') ? 'Kunci' : row[4] === 'Penutup' ? 'Kontrol' : 'Penunjang',
}))

export const DIMENSIONS = Array.from(new Set(INTERVIEW_QUESTIONS.map((q) => q.dimension)))
export const KEY_DIMENSIONS = DIMENSIONS.filter((dimension) => INTERVIEW_QUESTIONS.some((q) => q.dimension === dimension && q.role === 'Kunci'))
export const COMMON_PROBES = [...commonProbes]

export const READINESS_ITEMS = [
  'Catatan ANDOK dan rekomendasi Panel TPI telah dipetakan.',
  'Isu “Tidak Diusulkan” telah diterjemahkan menjadi pertanyaan klarifikasi atau ditetapkan NA.',
  'Karakteristik pegawai, perkara, layanan, dan riwayat evaluasi telah ditelaah.',
  'Laporan UPG/gratifikasi dan efektivitas WBS telah ditelaah.',
  'Sampel risiko BMN, anggaran, PBJ, dan biaya terkait perkara telah dipilih.',
  'Perwakilan pegawai nonpimpinan untuk uji acak telah disiapkan.',
  'Pembagian dimensi, lead evaluator, dan kendali waktu telah disepakati.',
  'Rekaman penuh/co-host dan bukti tambahan yang harus diminta telah disiapkan.',
] as const

export function blankResponse(): QuestionResponse {
  return { answer: '', evidence: '', consistency: 'belum', score: null, supportingResult: 'belum', redFlag: false, redFlagControlled: false, followUp: '', interviewer: '', asked: false, usedProbes: [] }
}
export function emptySnapshot(): InterviewSnapshot {
  return {
    version: 1,
    metadata: {},
    preparation: { andokIssues: [], readiness: {}, notes: '' },
    responses: Object.fromEntries(INTERVIEW_QUESTIONS.map((q) => [q.code, blankResponse()])),
    reconciliation: {},
    timer: { secondsRemaining: 90 * 60 },
  }
}
